"use node";

import { env } from "../../_lib/env.js";

const WRITTEN_QUESTIONS_CONFIG = {
  MAP_CHUNK_SIZE_TOKENS: parseInt(env.WRITTEN_QUESTIONS_MAP_CHUNK_TOKENS, 10),
  REDUCE_CHUNK_SIZE_TOKENS: parseInt(env.WRITTEN_QUESTIONS_REDUCE_CHUNK_TOKENS, 10),
  MIN_QUESTIONS_PER_CHUNK: parseInt(env.WRITTEN_QUESTIONS_MIN_QUESTIONS_PER_CHUNK, 10),
  MAX_QUESTIONS_PER_CHUNK: parseInt(env.WRITTEN_QUESTIONS_MAX_QUESTIONS_PER_CHUNK, 10),
  MIN_CHUNKS: parseInt(env.WRITTEN_QUESTIONS_MIN_CHUNKS, 10),
  MAP_TIMEOUT_MS: parseInt(env.WRITTEN_QUESTIONS_MAP_TIMEOUT_MS, 10),
  REDUCE_TIMEOUT_MS: parseInt(env.WRITTEN_QUESTIONS_REDUCE_TIMEOUT_MS, 10),
  REDUCE_MAX_TOKENS: parseInt(env.WRITTEN_QUESTIONS_REDUCE_MAX_TOKENS, 10),
  MAX_COLLAPSE_DEPTH: parseInt(env.WRITTEN_QUESTIONS_MAX_COLLAPSE_DEPTH, 10),
  DYNAMIC_BUFFER_MULTIPLIER: parseFloat(env.WRITTEN_QUESTIONS_DYNAMIC_BUFFER_MULTIPLIER),
  CHUNK_COVERAGE_THRESHOLD: parseFloat(env.WRITTEN_QUESTIONS_CHUNK_COVERAGE_THRESHOLD),
} as const;

export const GRAPH_CONFIG = {
  ...WRITTEN_QUESTIONS_CONFIG,
} as const;
