"use node";

export const GRAPH_CONFIG = {
  MAP_CHUNK_SIZE_TOKENS: 5_000,
  REDUCE_CHUNK_SIZE_TOKENS: 10_000,
  MIN_QUESTIONS_PER_CHUNK: 2,
  MAX_QUESTIONS_PER_CHUNK: 30,
  MIN_CHUNKS: 2,
  MAP_TIMEOUT_MS: 300_000, // 5 minutes
  REDUCE_TIMEOUT_MS: 300_000, // 5 minutes
  REDUCE_MAX_TOKENS: 32_000,
  MAX_COLLAPSE_DEPTH: 3,
  DYNAMIC_BUFFER_MULTIPLIER: 1.5,
  CHUNK_COVERAGE_THRESHOLD: 0.7,
} as const;
