import { z } from "zod";

/**
 * Structured chat response with citations.
 *
 * NOTE: Citations are extracted deterministically from the markdown text
 * ([1] or LaTeX-escaped \\[1\\]) rather than being generated by the LLM.
 * This ensures citations are always valid indices (1-N for N chunks).
 */
export interface ChatResponse {
  /** The answer in markdown format with inline citation markers */
  answer_markdown: string;
  /** Confidence level based on source coverage */
  confidence: "high" | "medium" | "low";
}

/**
 * Configuration for the LLM wrapper.
 */
export interface LLMWrapperConfig {
  /** TogetherAI API key */
  apiKey: string;
  /** Smart model for generation */
  model: string;
  /** Temperature for generation (default: 0.1) */
  temperature?: number;
  /** Fast model for lightweight operations (direct reply, follow-ups, subquery JSON). Falls back to smart model if omitted. */
  fastModel?: string;
  /** API key for fast model (defaults to apiKey) */
  fastApiKey?: string;
}

/**
 * Schema for structured chat response with citations.
 * This ensures the LLM returns properly formatted output.
 */
export const ChatResponseSchema = z.object({
  answer_markdown: z
    .string()
    .describe(
      "The answer in markdown format. " +
        "CRITICAL: Use INLINE citations ONLY - place plain ASCII [1], [2] after each factual claim (never \\[1\\] — backslashes break detection). " +
        'DO NOT add a "Sources:" footer or list at the end. ' +
        "Start with a direct answer, then provide supporting details with inline citations. " +
        "Math: wrap all formulas in $...$ or $$...$$; never use $ inside $$; do not nest dollar math."
    ),
  confidence: z
    .enum(["high", "medium", "low"])
    .describe(
      "Confidence level: " +
        "high = question directly addressed by 2+ sources with consistent information, " +
        "medium = question partially addressed or single source only, " +
        "low = tangential information or contradictory sources"
    ),
});
