"use node"
/**
 * LLM wrapper for chat agent.
 *
 * Handles structured output generation with citations using TogetherAI.
 * Optimized for token efficiency and reliable structured output.
 */

import { ChatTogetherAI } from '@langchain/community/chat_models/togetherai';
import { AIMessage, HumanMessage, SystemMessage } from '@langchain/core/messages';
import { z } from 'zod';
import type { ReferenceChunk } from '../../storage/ChatHistoryService';
import { createLangSmithRunConfig } from '../_shared/index.js';
import { uncachedLlmCall } from '../_shared/cachedLlm.js';
import { MARKDOWN_MATH_RULES_BULLETS } from '../_shared/markdownMathPrompt.js';
import { extractUniqueSortedCitationIndices } from '../_shared/citationExtract.js';

// ============================================================
// Types
// ============================================================

/**
 * Structured chat response with citations.
 *
 * NOTE: Citations are extracted deterministically from the markdown text
 * ([1] or LaTeX-escaped \\[1\\]) rather than being generated by the LLM.
 * This ensures citations are always valid indices (1-N for N chunks).
 */
export interface ChatResponse {
  /** The answer in markdown format with inline citation markers */
  answer_markdown: string;
  /** Confidence level based on source coverage */
  confidence: 'high' | 'medium' | 'low';
}

/**
 * Configuration for the LLM wrapper.
 */
export interface LLMWrapperConfig {
  /** TogetherAI API key */
  apiKey: string;
  /** Smart model for generation */
  model: string;
  /** Temperature for generation (default: 0.1) */
  temperature?: number;
  /** Fast model for lightweight operations (HyDE, follow-ups). Falls back to smart model if omitted. */
  fastModel?: string;
  /** API key for fast model (defaults to apiKey) */
  fastApiKey?: string;
}

// ============================================================
// Schemas
// ============================================================

/**
 * Schema for structured chat response with citations.
 * This ensures the LLM returns properly formatted output.
 */
export const ChatResponseSchema = z.object({
  answer_markdown: z
    .string()
    .describe(
      'The answer in markdown format. ' +
      'CRITICAL: Use INLINE citations ONLY - place plain ASCII [1], [2] after each factual claim (never \\[1\\] — backslashes break detection). ' +
      'DO NOT add a "Sources:" footer or list at the end. ' +
      'Start with a direct answer, then provide supporting details with inline citations. ' +
      'Math: wrap all formulas in $...$ or $$...$$; never use $ inside $$; do not nest dollar math.'
    ),
  confidence: z
    .enum(['high', 'medium', 'low'])
    .describe(
      'Confidence level: ' +
      'high = question directly addressed by 2+ sources with consistent information, ' +
      'medium = question partially addressed or single source only, ' +
      'low = tangential information or contradictory sources'
    ),
});

// ============================================================
// Constants
// ============================================================

/**
 * Streamlined core system prompt (optimized from ~2500 to ~800 tokens).
 */
const CORE_SYSTEM_PROMPT = `You are an expert research and learning assistant helping users understand their uploaded documents, notes, and study materials.

# MATH NOTATION FORMAT (STRICTLY ENFORCED)
${MARKDOWN_MATH_RULES_BULLETS}
- Greek letters: use $\\alpha$, $\\beta$, etc. inside math delimiters — not the word "alpha" alone for symbols.
- Do NOT use HTML entities (e.g. &lt;) or ANSI codes inside math.

# RESPONSE STRUCTURE GUIDANCE
When answering complex questions (comparisons, explanations, discussions):
1. Use clear section headers (###) for major topics
2. Cover ALL relevant aspects present in the source documents
3. Include a summary table or bullet points for comparisons
4. Prioritize completeness - don't skip important topics from the sources

# ULTRA-STRICT GROUNDING RULES
1. ONLY use information EXPLICITLY stated in the provided excerpts
2. Do NOT add examples, algorithm names, or technical terms not present in sources
3. Do NOT paraphrase heavily - stay close to source wording when citing
4. Do NOT make reasonable inferences - only state what sources directly say
5. If you want to mention something not in sources, say: "While not covered in your documents, [topic] typically involves..."

# CITATION FORMAT (CRITICAL - STRICTLY ENFORCED)
1. INLINE CITATIONS ONLY: Place [1], [2], etc. DIRECTLY AFTER each factual claim WITHIN sentences
2. NEVER add a "Sources:" or "References:" section at the end
3. DO NOT list all citations at the end - they must be scattered throughout your response
4. EVERY factual claim MUST have an inline citation right after it
5. Missing info? State: "Your documents don't cover [topic]"
6. NEVER cite a source for information you're inferring

# CITATION EXAMPLES (CORRECT):
- "Photosynthesis converts light energy into chemical energy [1]."
- "This process occurs in two stages: light-dependent reactions [1] and Calvin cycle [2]."
- "The drug inhibits enzyme X [1], reducing symptoms in 70% of patients [2]."

# CITATION EXAMPLES (WRONG - DO NOT DO THIS):
- "Photosynthesis converts light energy into chemical energy. Sources: [1]"
- "The drug inhibits enzyme X and reduces symptoms. [1][2]"

# WHEN CREATING TABLES
- Only include rows for information EXPLICITLY in sources
- Do NOT fill in cells with general knowledge
- If sources don't provide comparative data, say so instead of creating a table

# FORBIDDEN ADDITIONS
- Names/terms not mentioned in sources
- Examples not provided by sources
- "Typical" or "common" practices unless sources state them
- Diagrams or concepts not in sources

# PARAPHRASING RULES
When paraphrasing, stay VERY close to original wording:
- BAD: "The model is optimized to reproduce mappings [1]" (if source says "learns from labeled examples")
- GOOD: "The model learns from labeled examples [1]"

Your job is to REFLECT what the documents say, not enhance them with your training data.

# PROHIBITED CLOSINGS
- Do NOT end responses with meta-commentary like "Note: The above points are drawn directly from..."
- Do NOT add any closing disclaimers about what sources do or don't contain
- If sources are missing information, say so inline where relevant, then stop`;

/**
 * Minimal few-shot examples (only used for first query or complex patterns).
 * Aligned with actual schema - no extra fields.
 *
 * NOTE: Citations are extracted from markdown, not provided by LLM.
 */
const MINIMAL_FEW_SHOT = `
# EXAMPLES - Study these response patterns:

EXAMPLE 1: Conceptual Explanation
Q: "How does photosynthesis work?"
A: {
  "answer_markdown": "Photosynthesis is the process where plants convert light energy into chemical energy [1]. This occurs in two main stages: the light-dependent reactions and the Calvin cycle [1][2].\\n\\nDuring light-dependent reactions, chlorophyll absorbs photons and uses that energy to split water molecules, releasing oxygen as a byproduct [1]. This process generates ATP and NADPH [2], which serve as energy carriers.\\n\\nThe Calvin cycle uses this energy to fix atmospheric CO₂ into glucose [2]. It involves three phases: carbon fixation, reduction, and regeneration [2][3].\\n\\nYour documents explain the biochemical mechanisms [1][2] but don't discuss environmental factors affecting photosynthesis rates.\\n\\nNote: All citations above are INLINE - placed directly after each claim. No 'Sources:' footer at the end.",
  "confidence": "high"
}

EXAMPLE 2: Insufficient Information
Q: "What are the long-term effects of this drug?"
A: {
  "answer_markdown": "Your documents discuss the drug's mechanism of action [1] and short-term efficacy [2], but do not provide information about long-term effects.\\n\\nThe sources explain that the drug inhibits enzyme X [1], leading to reduced symptom severity in 70% of patients within 4 weeks [2]. However, studies longer than 12 weeks are not covered in these materials.\\n\\nRemember: Citations are INLINE throughout the text, not listed at the end.",
  "confidence": "low"
}

EXAMPLE 3: Comparative Analysis
Q: "What's the difference between mitosis and meiosis?"
A: {
  "answer_markdown": "Mitosis and meiosis are both cell division processes but serve different purposes [1].\\n\\n**Key Differences:**\\n| Aspect | Mitosis | Meiosis |\\n|--------|---------|---------|\\n| Purpose | Growth and repair [1] | Sexual reproduction [2] |\\n| Divisions | One division [1] | Two divisions [2] |\\n| Daughter Cells | 2 identical cells [1] | 4 genetically unique cells [2] |\\n| Chromosome Number | Maintained [1] | Halved [2] |\\n\\nMitosis produces diploid cells genetically identical to the parent [1], while meiosis creates haploid gametes with genetic variation through crossing over [2][3].\\n\\nNotice: Each fact has its inline citation immediately after it. No 'Sources:' section exists.",
  "confidence": "high"
}
`;

// ============================================================
// LLM Wrapper Class
// ============================================================

/**
 * Handles LLM response generation with structured output and citations.
 */
const STRICT_GROUNDING_PREFIX = `IMPORTANT: A previous response was flagged for insufficient grounding. This time, ONLY state things that are word-for-word supported by the sources. When in doubt, write: "The sources do not contain enough information to answer this."\n\n`;

export class ChatLLMWrapper {
  private llm: ChatTogetherAI;
  private fastLlm: ChatTogetherAI;
  /** Temp-0 smart LLM used for deterministic tool-calling/routing decisions. */
  private decisionLlm: ChatTogetherAI;
  /** Together model id for uncached follow-up calls (reasoning disabled). */
  private readonly fastLlmModelId: string;
  private tokenBudget: number = 7000; // Reserve tokens for generation

  constructor(config: LLMWrapperConfig) {
  // Smart model: allow template "thinking" / reasoning where the provider supports it
  // (e.g. hybrid Qwen, DeepSeek V3.1 on Together — see chat_template_kwargs in API).
  this.llm = new ChatTogetherAI({
    apiKey: config.apiKey,
    model: config.model,
    temperature: config.temperature ?? 0.1,
    modelKwargs: { chat_template_kwargs: { thinking: true } },
  });
  this.fastLlm = config.fastModel
    ? new ChatTogetherAI({
        apiKey: config.fastApiKey ?? config.apiKey,
        model: config.fastModel,
        temperature: 0.1,
        modelKwargs: { chat_template_kwargs: { thinking: false } },
      })
    : this.llm;
  this.fastLlmModelId = config.fastModel ?? config.model;
  // Deterministic routing — temp=0; disable thinking so tool JSON stays reliable
  this.decisionLlm = new ChatTogetherAI({
    apiKey: config.apiKey,
    model: config.model,
    temperature: 0,
    modelKwargs: { chat_template_kwargs: { thinking: false } },
  });
}

  /**
   * Returns the decision LLM with bound tools for the tool-calling loop.
   * Centralises ownership so ChatAgent doesn't need its own ChatTogetherAI instance.
   */
  bindDecisionTools(tools: any[]): any {
    return (this.decisionLlm as any).bindTools(tools);
  }

  /**
   * Generates a direct conversational response without RAG context.
   * Used when the routing LLM decides no document search is needed
   * (e.g. greetings, meta-questions about the app).
   */
  async generateDirectResponse(
    userMessage: string,
    conversationHistory: Array<{ role: string; content: string }>
  ): Promise<string> {
    console.log('[ChatLLMWrapper] Generating direct response (no RAG)');
    const systemPrompt =
      'You are a helpful study assistant. Answer the user conversationally and concisely. ' +
      'If they are asking about specific content from their documents, let them know you can search ' +
      'for it if they rephrase their question.';
    const messages = [
      new SystemMessage(systemPrompt),
      ...conversationHistory.slice(-4).map((t) =>
        t.role === 'user' ? new HumanMessage(t.content) : new AIMessage(t.content)
      ),
      new HumanMessage(userMessage),
    ];
    try {
      const response = await this.fastLlm.invoke(messages);
      return typeof response.content === 'string'
        ? response.content.trim()
        : String(response.content).trim();
    } catch (error) {
      console.warn('[ChatLLMWrapper] Direct response failed:', error);
      return "I'm here to help! Ask me anything about your study materials.";
    }
  }

  /**
   * Generates a hypothetical document paragraph for HyDE retrieval.
   * The caller typically embeds this together with the declarative search query so
   * explicit keywords stay represented while HyDE improves semantic density.
   */
  async generateHypotheticalDocument(query: string): Promise<string> {
    console.log('[ChatLLMWrapper] Generating hypothetical document for HyDE');
    const prompt = `Write a short, factual paragraph (2–5 sentences) that would directly address this information need if it appeared in a textbook or study note. Write as plain statements of fact, not as dialogue or Q&A.

Coverage rules (for retrieval — follow even if you are unsure of fine details):
- If the question compares or contrasts multiple methods, concepts, named entities, cases, or time periods, give EACH distinct subject at least one clear sentence. Do not let the first or most familiar subject consume the whole paragraph or leave other named subjects out.
- If the question asks how A relates to B (difference, similarity, tradeoff), describe both A and B (or every side listed), not only one.
- Include important proper nouns and technical terms from the question using normal spacing between words.

Question: ${query}`;
    try {
      const response = await uncachedLlmCall({
        model: this.fastLlmModelId,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.1,
        maxTokens: 220,
        reasoningEnabled: false,
        toolChoice: 'none',
      });
      const text = response.content.trim();
      console.log('[ChatLLMWrapper] HyDE document:', text.slice(0, 200));
      return text || query;
    } catch (error) {
      console.warn('[ChatLLMWrapper] HyDE generation failed, falling back to raw query:', error);
      return query;
    }
  }

  /**
   * Generates 2-3 follow-up question suggestions for a study session.
   */
  async generateFollowUpQuestions(userMessage: string, answer: string): Promise<string[]> {
    console.log('[ChatLLMWrapper] Generating follow-up questions');
    const truncatedAnswer = answer.length > 600 ? answer.slice(0, 600) + '...' : answer;
    const prompt = `You are helping a student study. Based on this Q&A, suggest 2-3 short follow-up questions the student might naturally ask next.\n\nQuestion: ${userMessage}\nAnswer: ${truncatedAnswer}\n\nReturn ONLY a JSON array of strings, e.g. ["Question 1?", "Question 2?", "Question 3?"]`;
    try {
      const response = await uncachedLlmCall({
        model: this.fastLlmModelId,
        messages: [
          {
            role: 'system',
            content:
              'Reply with ONLY a JSON array of 2-3 short question strings. No markdown, no tools, and no text before or after the array.',
          },
          { role: 'user', content: prompt },
        ],
        temperature: 0.35,
        maxTokens: 320,
        reasoningEnabled: false,
        toolChoice: 'none',
      });
      const text = response.content.trim();
      // Strip Qwen-style <think>...</think> reasoning blocks before parsing
      const stripped = text.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
      const match = stripped.match(/\[[\s\S]*\]/);
      if (match) {
        const parsed = JSON.parse(match[0]);
        if (Array.isArray(parsed)) {
          return parsed.slice(0, 3).map(String).filter(Boolean);
        }
      }
      return [];
    } catch (error) {
      console.warn('[ChatLLMWrapper] Follow-up question generation failed:', error);
      return [];
    }
  }

  /**
   * Re-generates a response with stricter grounding constraints after a validation failure.
   */
  async generateWithStrictGrounding(
    chunks: ReferenceChunk[],
    userMessage: string,
    conversationHistory: Array<{ role: string; content: string }> = []
  ): Promise<ChatResponse> {
    console.log('[ChatLLMWrapper] Retrying with strict grounding');
    return this._generateStructuredResponse(chunks, userMessage, conversationHistory, true);
  }

  /**
   * Generates a structured response with citations using tool calling.
   *
   * @param chunks - Reference chunks to use as context
   * @param userMessage - The user's question
   * @param conversationHistory - Previous conversation turns for context
   * @returns Structured chat response with citations
   */
  async generateStructuredResponse(
    chunks: ReferenceChunk[],
    userMessage: string,
    conversationHistory: Array<{ role: string; content: string }> = []
  ): Promise<ChatResponse> {
    return this._generateStructuredResponse(chunks, userMessage, conversationHistory, false);
  }

  private async _generateStructuredResponse(
    chunks: ReferenceChunk[],
    userMessage: string,
    conversationHistory: Array<{ role: string; content: string }>,
    strictGrounding: boolean
  ): Promise<ChatResponse> {
    console.log('[ChatLLMWrapper] Generating structured response with citations');

    // Conditional few-shot: only for first query or complex patterns
    const needsExamples = conversationHistory.length === 0 || this.isComplexQuery(userMessage);

    // Inject current date so the model knows "today" vs historical document dates
    const today = new Date().toISOString().split('T')[0];
    const dateContext = `\nCurrent Date: ${today}`;

    const basePrompt = needsExamples
      ? `${MINIMAL_FEW_SHOT}\n\n${CORE_SYSTEM_PROMPT}${dateContext}`
      : `${CORE_SYSTEM_PROMPT}${dateContext}`;
    const systemPrompt = strictGrounding ? `${STRICT_GROUNDING_PREFIX}${basePrompt}` : basePrompt;

    // Create model with structured output
    // Use 'any' to avoid deep type instantiation issues
    const structuredLlm = (this.llm as any).withStructuredOutput(ChatResponseSchema, {
      name: 'chat_response',
    });

    const groundedPrompt = this.buildGroundingPrompt(chunks, userMessage, conversationHistory);

    // Debug: Log the full prompt (truncated if too long)
    console.log('[ChatLLMWrapper] Full grounded prompt (first 2000 chars):', groundedPrompt.slice(0, 2000));

    // Token monitoring
    const systemTokens = this.estimateTokens(systemPrompt);
    const userTokens = this.estimateTokens(groundedPrompt);
    const totalTokens = systemTokens + userTokens;

    console.log(
      `[ChatLLMWrapper] Token usage: system=${systemTokens}, user=${userTokens}, total=${totalTokens}`
    );

    if (totalTokens > this.tokenBudget) {
      console.warn(
        `[ChatLLMWrapper] High token usage (${totalTokens}/${this.tokenBudget}). Consider reducing chunk count.`
      );
    }

    const messages = [new SystemMessage(systemPrompt), new HumanMessage(groundedPrompt)];
    const traceConfig = createLangSmithRunConfig({
      runName: 'ChatAgentStructuredResponse',
      tags: ['agent', 'chat'],
      metadata: {
        chunksCount: chunks.length,
        conversationHistoryCount: conversationHistory.length,
      },
    });

    try {
      const response: any = await structuredLlm.invoke(messages, traceConfig);
      // Validate the response matches our schema
      const validated = ChatResponseSchema.safeParse(response);

      if (!validated.success) {
        console.warn(
          '[ChatLLMWrapper] Structured output validation failed:',
          validated.error.issues
        );

        // Attempt to salvage the response
        const salvaged = this.salvageResponse(response);
        if (salvaged) {
          console.log('[ChatLLMWrapper] Successfully salvaged response after validation failure');
          return salvaged;
        }

        // True failure - return error response
        return {
          answer_markdown: 'I encountered an error. Please rephrase your question or try again.',
          confidence: 'low',
        };
      }

      console.log('[ChatLLMWrapper] Structured response generated successfully');
      console.log(`[ChatLLMWrapper] Full response markdown: "${validated.data.answer_markdown}"`);

      // Extract citations from markdown for logging
      const extractedCitations = this.extractCitationsFromMarkdown(validated.data.answer_markdown);
      console.log(
        `[ChatLLMWrapper] Citations: [${extractedCitations.join(', ')}], Confidence: ${validated.data.confidence}`
      );

      // Ensure all required fields are present
      return {
        answer_markdown: validated.data.answer_markdown ?? '',
        confidence: validated.data.confidence ?? 'low',
      } as ChatResponse;
    } catch (error) {
      console.error('[ChatLLMWrapper] Structured output generation failed:', error);
      return {
        answer_markdown:
          'I apologize, but I encountered an error generating a response. Please try again.',
        confidence: 'low',
      };
    }
  }

  /**
   * Builds grounding prompt optimized for research/learning contexts.
   * Enhanced with chunk metadata for better context awareness.
   */
  private buildGroundingPrompt(
    chunks: ReferenceChunk[],
    userMessage: string,
    conversationHistory: Array<{ role: string; content: string }>
  ): string {
    // Enhanced chunk formatting with metadata
    const formattedChunks = chunks
      .map((chunk, index) => {
        const meta = chunk.metadata;
        const docType = this.inferDocumentType(chunk.sourceTitle);
        const typeLabel = docType ? ` (${docType})` : '';

        // Build hierarchical context header
        let contextHeader = `[${index + 1}] From "${chunk.sourceTitle}"${typeLabel}`;

        // Add section hierarchy if available
        if (meta?.headingPath && meta.headingPath.length > 0) {
          contextHeader += ` > ${meta.headingPath.join(' > ')}`;
        } else if (meta?.sectionTitle) {
          contextHeader += ` > ${meta.sectionTitle}`;
        }

        // Add position context
        const positionInfo: string[] = [];
        if (meta?.pageNumber !== undefined && meta.pageNumber !== null) {
          positionInfo.push(`Page ${meta.pageNumber}`);
        }
        if (meta?.relativePosition !== undefined) {
          const position = meta.relativePosition < 0.33 ? 'Beginning' :
                           meta.relativePosition < 0.67 ? 'Middle' : 'End';
          positionInfo.push(`${position} of document`);
        }
        if (positionInfo.length > 0) {
          contextHeader += ` (${positionInfo.join(', ')})`;
        }

        // Add content characteristics
        const characteristics: string[] = [];
        if (meta?.hasCodeBlock) characteristics.push('Contains code');
        if (meta?.hasMathNotation) characteristics.push('Contains formulas');
        if (meta?.hasTable) characteristics.push('Contains table');
        if (characteristics.length > 0) {
          contextHeader += `\n[${characteristics.join(', ')}]`;
        }

        // SANITIZE: Remove existing bracketed numbers from content to prevent LLM confusion
        const sanitizedContent = chunk.content.replace(/\[\d+\]/g, '');

        // Add neighboring context for continuity
        let contentWithContext = '';

        if (meta?.previousChunkPreview) {
          contentWithContext += `...${meta.previousChunkPreview}\n\n`;
        }

        contentWithContext += sanitizedContent;

        if (meta?.nextChunkPreview) {
          contentWithContext += `\n\n${meta.nextChunkPreview}...`;
        }

        const formatted = `${contextHeader}:\n${contentWithContext}`;

        // Log each chunk for debugging
        console.log(`[ChatLLMWrapper] Chunk [${index + 1}] (db chunkIndex=${chunk.chunkIndex}):`, {
          sourceTitle: chunk.sourceTitle,
          sectionTitle: meta?.sectionTitle,
          headingPath: meta?.headingPath,
          relativePosition: meta?.relativePosition,
          contentPreview: sanitizedContent.slice(0, 200),
        });

        return formatted;
      })
      .join('\n\n---\n\n');

    // Conversation context - include both user questions AND assistant responses
    // This allows the LLM to understand follow-up questions like "Can you simplify that?"
    let contextSection = '';
    if (conversationHistory.length > 0) {
      const formattedHistory = conversationHistory
        .map((msg) => {
          const role = msg.role === 'user' ? 'USER' : 'ASSISTANT';
          // Truncate long responses to avoid context bloat
          const truncatedContent = msg.content.length > 500 
            ? msg.content.slice(0, 500) + '...' 
            : msg.content;
          return `${role}: ${truncatedContent}`;
        })
        .join('\n');
      contextSection = `# CONVERSATION HISTORY\n${formattedHistory}\n\n`;
    }

    // Ultra-concise query type hint
    const structureHint = this.getStructureHint(userMessage);

    // Always include citation format reminder at the TOP of the user prompt
    // This ensures it's seen even for follow-up questions where few-shot isn't used
    const citationReminder = `# CITATION FORMAT (MANDATORY)
- Place [1], [2] DIRECTLY AFTER each fact within sentences (plain brackets only — not \\[1\\])
- Example: "uv is a Python package [1] designed for speed [2]."
- DO NOT add "Sources:" or "References:" at the end
- Every factual claim needs its inline citation

# MATH FORMAT (MANDATORY WHEN USING EQUATIONS)
${MARKDOWN_MATH_RULES_BULLETS}
- Example (inline): "The level $L_t$ evolves as $L_t = \\alpha y_t + (1-\\alpha) L_{t-1}$ [1]."
- Example (display): $$L_t = \\alpha y_t + (1-\\alpha) L_{t-1}$$
- Never write L_t, B_{t-1}, \\eta, or neta without delimiters — they will not render.

# RESPONSE FORMATTING (MANDATORY)
- Use **bold** for key terms when introducing concepts
- Use ### headers for major sections in comparison/explanation responses
- Use markdown tables for side-by-side comparisons when appropriate
- Use numbered lists for sequential steps or ordered items
- Use bullet points for unordered lists of features/properties

`;

    return `# SOURCE DOCUMENTS
${formattedChunks}

${contextSection}${citationReminder}# CURRENT QUESTION
${userMessage}

${structureHint}`;
  }

  /**
   * Provides ultra-concise structure hint based on query type.
   * Includes negative constraints for better adherence.
   */
  private getStructureHint(query: string): string {
    const lower = query.toLowerCase();

    // General comparison/difference hints - works for any domain
    if (lower.match(/compare|contrast|difference|differ|vs|versus/)) {
      return `Hint: Structure your comparison with clear sections:
1. **Core Definition** - What is each thing?
2. **Key Differences** - How do they fundamentally differ?
3. **Characteristics/Properties** - What are their distinct features?
4. **Use Cases/Context** - When is each appropriate?
5. **Relationships** - How do they relate to each other?

Include a summary table at the end comparing key features.
Do not write block paragraphs for comparisons.`;
    }

    if (lower.match(/equation|formula|formulas|math|latex|notation|subscript|superscript/)) {
      return (
        'Hint: Use $...$ for inline and $$...$$ for full display equations; never put $ inside $$; ' +
        'do not nest dollar math (e.g. avoid \\cmd($x$)); wrap every symbolic variable in delimiters (write $x$, not bare x).'
      );
    }

    if (lower.match(/^(how|why|explain)/)) {
      return 'Hint: Definition → mechanism/process → examples (if available in sources). Do not provide generic examples not in sources.';
    }

    if (lower.match(/summarize|overview|main points|key takeaways/)) {
      return 'Hint: Main themes → key findings → gaps or questions.';
    }

    // General "discuss" or "describe" questions - encourage comprehensive coverage
    if (lower.match(/^discuss|describe|overview of|types of|kinds of|what are/)) {
      return 'Hint: Cover ALL major aspects mentioned in the sources. Use sections or lists for clarity. Check that you have not skipped important topics present in the documents.';
    }

    // List/enumeration questions
    if (lower.match(/list|enumerate/)) {
      return 'Hint: Use numbered or bulleted lists for clarity. Include citations after each item.';
    }

    return '';
  }

  /**
   * Checks if query is complex and needs few-shot examples.
   */
  private isComplexQuery(query: string): boolean {
    const complexPatterns = [
      'compare',
      'contrast',
      'explain how',
      'why does',
      'difference between',
    ];
    const lower = query.toLowerCase();
    return complexPatterns.some((pattern) => lower.includes(pattern));
  }

  /**
   * Infers document type from title for better context.
   */
  private inferDocumentType(title: string): string | null {
    const lower = title.toLowerCase();

    if (lower.includes('chapter') || lower.includes('textbook')) return 'Textbook';
    if (lower.includes('lecture')) return 'Lecture';
    if (lower.includes('paper') || lower.includes('journal')) return 'Paper';
    if (lower.includes('notes')) return 'Notes';
    if (lower.includes('slides')) return 'Slides';

    return null;
  }

  /**
   * Estimates token count (rough approximation: 1 token ≈ 4 characters).
   */
  private estimateTokens(text: string): number {
    return Math.ceil(text.length / 4);
  }

  /**
   * Extracts citation indices from markdown text using regex.
   * This deterministically extracts all [1], [2], etc. citations from the text.
   *
   * @param text - The markdown text to extract citations from
   * @returns Sorted array of unique citation indices (1-indexed)
   */
  private extractCitationsFromMarkdown(text: string): number[] {
    return extractUniqueSortedCitationIndices(text);
  }

  /**
   * Attempts to salvage a malformed response by extracting usable parts.
   */
  private salvageResponse(response: any): ChatResponse | null {
    try {
      // Extract answer text from various possible formats
      let answerText = '';
      if (typeof response === 'string') {
        answerText = response;
      } else if (response?.answer_markdown) {
        answerText = String(response.answer_markdown);
      } else if (response?.answer) {
        answerText = String(response.answer);
      } else {
        return null;
      }

      // Extract citation indices from the text (using helper method)
      const citedIndices = this.extractCitationsFromMarkdown(answerText);

      // Determine confidence from text patterns
      const hasHedging = /\b(probably|might|maybe|perhaps|possibly|could be|it seems)\b/i.test(
        answerText
      );
      const hasMissingInfo = /don't have information|not covered|doesn't (explain|discuss|address)/i.test(
        answerText
      );

      const confidence =
        citedIndices.length >= 3 && !hasHedging
          ? 'high'
          : citedIndices.length >= 1 && !hasMissingInfo
            ? 'medium'
            : 'low';

      return {
        answer_markdown: answerText,
        confidence,
      };
    } catch (error) {
      console.error('[ChatLLMWrapper] Salvage attempt failed:', error);
      return null;
    }
  }
}
