/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as ResendOTP from "../ResendOTP.js";
import type * as ResendOTPPasswordReset from "../ResendOTPPasswordReset.js";
import type * as _agents_AudioOverviewGraph from "../_agents/AudioOverviewGraph.js";
import type * as _agents_ChatAgent from "../_agents/ChatAgent.js";
import type * as _agents_FlashcardGraph from "../_agents/FlashcardGraph.js";
import type * as _agents_MindMapGraph from "../_agents/MindMapGraph.js";
import type * as _agents_QuizGraph from "../_agents/QuizGraph.js";
import type * as _agents_ReportGraph from "../_agents/ReportGraph.js";
import type * as _agents_SpreadsheetGraph from "../_agents/SpreadsheetGraph.js";
import type * as _agents_WrittenQuestionsGraph from "../_agents/WrittenQuestionsGraph.js";
import type * as _agents__shared_agent_graph_limits from "../_agents/_shared/agent_graph_limits.js";
import type * as _agents__shared_cachedLlm from "../_agents/_shared/cachedLlm.js";
import type * as _agents__shared_chunk_helper_factory from "../_agents/_shared/chunk_helper_factory.js";
import type * as _agents__shared_chunk_operations from "../_agents/_shared/chunk_operations.js";
import type * as _agents__shared_citationExtract from "../_agents/_shared/citationExtract.js";
import type * as _agents__shared_concurrency from "../_agents/_shared/concurrency.js";
import type * as _agents__shared_graph_builder from "../_agents/_shared/graph_builder.js";
import type * as _agents__shared_index from "../_agents/_shared/index.js";
import type * as _agents__shared_jobHelpers from "../_agents/_shared/jobHelpers.js";
import type * as _agents__shared_languageInstruction from "../_agents/_shared/languageInstruction.js";
import type * as _agents__shared_llm_factory from "../_agents/_shared/llm_factory.js";
import type * as _agents__shared_logging from "../_agents/_shared/logging.js";
import type * as _agents__shared_markdownMathPrompt from "../_agents/_shared/markdownMathPrompt.js";
import type * as _agents__shared_node_builder from "../_agents/_shared/node_builder.js";
import type * as _agents__shared_progress from "../_agents/_shared/progress.js";
import type * as _agents__shared_retry from "../_agents/_shared/retry.js";
import type * as _agents__shared_sanitization from "../_agents/_shared/sanitization.js";
import type * as _agents__shared_stateUpdateHelpers from "../_agents/_shared/stateUpdateHelpers.js";
import type * as _agents__shared_state_cleanup from "../_agents/_shared/state_cleanup.js";
import type * as _agents__shared_state_factory from "../_agents/_shared/state_factory.js";
import type * as _agents__shared_timeout from "../_agents/_shared/timeout.js";
import type * as _agents__shared_tokenizer from "../_agents/_shared/tokenizer.js";
import type * as _agents__shared_topic_extraction from "../_agents/_shared/topic_extraction.js";
import type * as _agents__shared_validation from "../_agents/_shared/validation.js";
import type * as _agents_audio_overview_AudioOverviewGraph from "../_agents/audio_overview/AudioOverviewGraph.js";
import type * as _agents_audio_overview_chunkHelpers from "../_agents/audio_overview/chunkHelpers.js";
import type * as _agents_audio_overview_config from "../_agents/audio_overview/config.js";
import type * as _agents_audio_overview_nodeCollapse from "../_agents/audio_overview/nodeCollapse.js";
import type * as _agents_audio_overview_nodeExtractBeats from "../_agents/audio_overview/nodeExtractBeats.js";
import type * as _agents_audio_overview_nodeSynthesizeAudio from "../_agents/audio_overview/nodeSynthesizeAudio.js";
import type * as _agents_audio_overview_nodeWriteScript from "../_agents/audio_overview/nodeWriteScript.js";
import type * as _agents_audio_overview_prompts from "../_agents/audio_overview/prompts.js";
import type * as _agents_audio_overview_scriptParsing from "../_agents/audio_overview/scriptParsing.js";
import type * as _agents_audio_overview_state from "../_agents/audio_overview/state.js";
import type * as _agents_audio_overview_voices from "../_agents/audio_overview/voices.js";
import type * as _agents_chat_ChatAgent from "../_agents/chat/ChatAgent.js";
import type * as _agents_chat_chatConfig from "../_agents/chat/chatConfig.js";
import type * as _agents_chat_chatHistoryBudget from "../_agents/chat/chatHistoryBudget.js";
import type * as _agents_chat_chatRouter from "../_agents/chat/chatRouter.js";
import type * as _agents_chat_chat_llm_grounding from "../_agents/chat/chat_llm_grounding.js";
import type * as _agents_chat_chat_llm_prompts from "../_agents/chat/chat_llm_prompts.js";
import type * as _agents_chat_chat_llm_types from "../_agents/chat/chat_llm_types.js";
import type * as _agents_chat_chat_retrieval_subqueries from "../_agents/chat/chat_retrieval_subqueries.js";
import type * as _agents_chat_chunkContext from "../_agents/chat/chunkContext.js";
import type * as _agents_chat_grounding_validator from "../_agents/chat/grounding_validator.js";
import type * as _agents_chat_hybrid_search from "../_agents/chat/hybrid_search.js";
import type * as _agents_chat_llm_wrapper from "../_agents/chat/llm_wrapper.js";
import type * as _agents_chat_queryExpansion from "../_agents/chat/queryExpansion.js";
import type * as _agents_chat_rerankCache from "../_agents/chat/rerankCache.js";
import type * as _agents_chat_searchQueryRefiner from "../_agents/chat/searchQueryRefiner.js";
import type * as _agents_chat_sourceSuggestions from "../_agents/chat/sourceSuggestions.js";
import type * as _agents_chat_streamSlice from "../_agents/chat/streamSlice.js";
import type * as _agents_chat_types from "../_agents/chat/types.js";
import type * as _agents_chat_vector_search from "../_agents/chat/vector_search.js";
import type * as _agents_chat_withTimeout from "../_agents/chat/withTimeout.js";
import type * as _agents_flashcard_FlashcardGraph from "../_agents/flashcard/FlashcardGraph.js";
import type * as _agents_flashcard_chunkHelpers from "../_agents/flashcard/chunkHelpers.js";
import type * as _agents_flashcard_collapseReduceLlm from "../_agents/flashcard/collapseReduceLlm.js";
import type * as _agents_flashcard_config from "../_agents/flashcard/config.js";
import type * as _agents_flashcard_flashcardHeuristics from "../_agents/flashcard/flashcardHeuristics.js";
import type * as _agents_flashcard_formatFlashcards from "../_agents/flashcard/formatFlashcards.js";
import type * as _agents_flashcard_nodeCollapse from "../_agents/flashcard/nodeCollapse.js";
import type * as _agents_flashcard_nodeMap from "../_agents/flashcard/nodeMap.js";
import type * as _agents_flashcard_nodeReduce from "../_agents/flashcard/nodeReduce.js";
import type * as _agents_flashcard_nodeSplit from "../_agents/flashcard/nodeSplit.js";
import type * as _agents_flashcard_prompts from "../_agents/flashcard/prompts.js";
import type * as _agents_flashcard_routing from "../_agents/flashcard/routing.js";
import type * as _agents_flashcard_state from "../_agents/flashcard/state.js";
import type * as _agents_flashcard_structuredLlm from "../_agents/flashcard/structuredLlm.js";
import type * as _agents_flashcard_textCleanup from "../_agents/flashcard/textCleanup.js";
import type * as _agents_literature_review_LiteratureReviewGraph from "../_agents/literature_review/LiteratureReviewGraph.js";
import type * as _agents_literature_review_planReviewColumns from "../_agents/literature_review/planReviewColumns.js";
import type * as _agents_literature_review_prompts from "../_agents/literature_review/prompts.js";
import type * as _agents_literature_review_state from "../_agents/literature_review/state.js";
import type * as _agents_literature_review_types from "../_agents/literature_review/types.js";
import type * as _agents_mindmap_MindMapGraph from "../_agents/mindmap/MindMapGraph.js";
import type * as _agents_mindmap_chunkHelpers from "../_agents/mindmap/chunkHelpers.js";
import type * as _agents_mindmap_config from "../_agents/mindmap/config.js";
import type * as _agents_mindmap_fallbacks from "../_agents/mindmap/fallbacks.js";
import type * as _agents_mindmap_nodeMap from "../_agents/mindmap/nodeMap.js";
import type * as _agents_mindmap_nodeReduce from "../_agents/mindmap/nodeReduce.js";
import type * as _agents_mindmap_parsing from "../_agents/mindmap/parsing.js";
import type * as _agents_mindmap_prompts from "../_agents/mindmap/prompts.js";
import type * as _agents_mindmap_routing from "../_agents/mindmap/routing.js";
import type * as _agents_mindmap_state from "../_agents/mindmap/state.js";
import type * as _agents_mindmap_structuredLlm from "../_agents/mindmap/structuredLlm.js";
import type * as _agents_quiz_QuizGraph from "../_agents/quiz/QuizGraph.js";
import type * as _agents_quiz_chunkHelpers from "../_agents/quiz/chunkHelpers.js";
import type * as _agents_quiz_config from "../_agents/quiz/config.js";
import type * as _agents_quiz_nodeCollapse from "../_agents/quiz/nodeCollapse.js";
import type * as _agents_quiz_nodeMap from "../_agents/quiz/nodeMap.js";
import type * as _agents_quiz_nodeReduce from "../_agents/quiz/nodeReduce.js";
import type * as _agents_quiz_nodeSplit from "../_agents/quiz/nodeSplit.js";
import type * as _agents_quiz_optionLabels from "../_agents/quiz/optionLabels.js";
import type * as _agents_quiz_postprocess from "../_agents/quiz/postprocess.js";
import type * as _agents_quiz_prompts from "../_agents/quiz/prompts.js";
import type * as _agents_quiz_quizHeuristics from "../_agents/quiz/quizHeuristics.js";
import type * as _agents_quiz_routing from "../_agents/quiz/routing.js";
import type * as _agents_quiz_state from "../_agents/quiz/state.js";
import type * as _agents_quiz_structuredLlm from "../_agents/quiz/structuredLlm.js";
import type * as _agents_report_ReportGraph from "../_agents/report/ReportGraph.js";
import type * as _agents_report_chunkHelpers from "../_agents/report/chunkHelpers.js";
import type * as _agents_report_config from "../_agents/report/config.js";
import type * as _agents_report_inputValidation from "../_agents/report/inputValidation.js";
import type * as _agents_report_invokeHelpers from "../_agents/report/invokeHelpers.js";
import type * as _agents_report_nodeCollapse from "../_agents/report/nodeCollapse.js";
import type * as _agents_report_nodeMap from "../_agents/report/nodeMap.js";
import type * as _agents_report_nodeMerge from "../_agents/report/nodeMerge.js";
import type * as _agents_report_nodeReduce from "../_agents/report/nodeReduce.js";
import type * as _agents_report_nodes from "../_agents/report/nodes.js";
import type * as _agents_report_prompts from "../_agents/report/prompts.js";
import type * as _agents_report_routing from "../_agents/report/routing.js";
import type * as _agents_report_state from "../_agents/report/state.js";
import type * as _agents_report_structuredLlm from "../_agents/report/structuredLlm.js";
import type * as _agents_report_topicAnalysis from "../_agents/report/topicAnalysis.js";
import type * as _agents_research_DeepResearchGraph from "../_agents/research/DeepResearchGraph.js";
import type * as _agents_research_graph from "../_agents/research/graph.js";
import type * as _agents_research_index from "../_agents/research/index.js";
import type * as _agents_research_nodes from "../_agents/research/nodes.js";
import type * as _agents_research_prompts from "../_agents/research/prompts.js";
import type * as _agents_research_state from "../_agents/research/state.js";
import type * as _agents_research_steps from "../_agents/research/steps.js";
import type * as _agents_research_types from "../_agents/research/types.js";
import type * as _agents_spreadsheet_SpreadsheetGraph from "../_agents/spreadsheet/SpreadsheetGraph.js";
import type * as _agents_spreadsheet_chunkHelpers from "../_agents/spreadsheet/chunkHelpers.js";
import type * as _agents_spreadsheet_config from "../_agents/spreadsheet/config.js";
import type * as _agents_spreadsheet_csvHelpers from "../_agents/spreadsheet/csvHelpers.js";
import type * as _agents_spreadsheet_inputValidation from "../_agents/spreadsheet/inputValidation.js";
import type * as _agents_spreadsheet_nodeCollapse from "../_agents/spreadsheet/nodeCollapse.js";
import type * as _agents_spreadsheet_nodeMap from "../_agents/spreadsheet/nodeMap.js";
import type * as _agents_spreadsheet_nodeMerge from "../_agents/spreadsheet/nodeMerge.js";
import type * as _agents_spreadsheet_nodeReduce from "../_agents/spreadsheet/nodeReduce.js";
import type * as _agents_spreadsheet_prompts from "../_agents/spreadsheet/prompts.js";
import type * as _agents_spreadsheet_routing from "../_agents/spreadsheet/routing.js";
import type * as _agents_spreadsheet_state from "../_agents/spreadsheet/state.js";
import type * as _agents_written_questions_WrittenQuestionsGraph from "../_agents/written_questions/WrittenQuestionsGraph.js";
import type * as _agents_written_questions_chunkHelpers from "../_agents/written_questions/chunkHelpers.js";
import type * as _agents_written_questions_config from "../_agents/written_questions/config.js";
import type * as _agents_written_questions_nodeCollapse from "../_agents/written_questions/nodeCollapse.js";
import type * as _agents_written_questions_nodeMap from "../_agents/written_questions/nodeMap.js";
import type * as _agents_written_questions_nodeReduce from "../_agents/written_questions/nodeReduce.js";
import type * as _agents_written_questions_nodeSplit from "../_agents/written_questions/nodeSplit.js";
import type * as _agents_written_questions_postprocess from "../_agents/written_questions/postprocess.js";
import type * as _agents_written_questions_prompts from "../_agents/written_questions/prompts.js";
import type * as _agents_written_questions_questionHeuristics from "../_agents/written_questions/questionHeuristics.js";
import type * as _agents_written_questions_routing from "../_agents/written_questions/routing.js";
import type * as _agents_written_questions_state from "../_agents/written_questions/state.js";
import type * as _agents_written_questions_structuredLlm from "../_agents/written_questions/structuredLlm.js";
import type * as _lib_arxivThrottle from "../_lib/arxivThrottle.js";
import type * as _lib_conversationAccess from "../_lib/conversationAccess.js";
import type * as _lib_e5Embedding from "../_lib/e5Embedding.js";
import type * as _lib_env from "../_lib/env.js";
import type * as _lib_errors from "../_lib/errors.js";
import type * as _lib_externalProviderCooldowns from "../_lib/externalProviderCooldowns.js";
import type * as _lib_googleDriveDownload from "../_lib/googleDriveDownload.js";
import type * as _lib_limits from "../_lib/limits.js";
import type * as _lib_logging_serviceLogger from "../_lib/logging/serviceLogger.js";
import type * as _lib_notebookAccess from "../_lib/notebookAccess.js";
import type * as _lib_queryCaps from "../_lib/queryCaps.js";
import type * as _lib_rateLimits from "../_lib/rateLimits.js";
import type * as _lib_resendSendError from "../_lib/resendSendError.js";
import type * as _lib_resolveSmartModel from "../_lib/resolveSmartModel.js";
import type * as _lib_semanticScholarThrottle from "../_lib/semanticScholarThrottle.js";
import type * as _lib_serviceErrors from "../_lib/serviceErrors.js";
import type * as _lib_shareToken from "../_lib/shareToken.js";
import type * as _lib_srsScheduling from "../_lib/srsScheduling.js";
import type * as _lib_utils_urlValidation from "../_lib/utils/urlValidation.js";
import type * as _migration_index from "../_migration/index.js";
import type * as _migration_reembedBatchesWorker from "../_migration/reembedBatchesWorker.js";
import type * as _migration_reembedChunks from "../_migration/reembedChunks.js";
import type * as _migration_removeSlidePrompts from "../_migration/removeSlidePrompts.js";
import type * as _model_audioOverviews from "../_model/audioOverviews.js";
import type * as _model_conversations from "../_model/conversations.js";
import type * as _model_documents from "../_model/documents.js";
import type * as _model_flashcards from "../_model/flashcards.js";
import type * as _model_folders from "../_model/folders.js";
import type * as _model_infographics from "../_model/infographics.js";
import type * as _model_literatureReviewSearchOptions from "../_model/literatureReviewSearchOptions.js";
import type * as _model_mindmaps from "../_model/mindmaps.js";
import type * as _model_notebooks from "../_model/notebooks.js";
import type * as _model_notes from "../_model/notes.js";
import type * as _model_quizzes from "../_model/quizzes.js";
import type * as _model_reports from "../_model/reports.js";
import type * as _model_spreadsheets from "../_model/spreadsheets.js";
import type * as _model_writtenQuestions from "../_model/writtenQuestions.js";
import type * as _services_ai_embeddings from "../_services/ai/embeddings.js";
import type * as _services_ai_mp3 from "../_services/ai/mp3.js";
import type * as _services_ai_titleGenerator from "../_services/ai/titleGenerator.js";
import type * as _services_ai_togetherClient from "../_services/ai/togetherClient.js";
import type * as _services_ai_togetherImages from "../_services/ai/togetherImages.js";
import type * as _services_ai_togetherTts from "../_services/ai/togetherTts.js";
import type * as _services_ai_wav from "../_services/ai/wav.js";
import type * as _services_cache_cache from "../_services/cache/cache.js";
import type * as _services_cache_cacheCrypto from "../_services/cache/cacheCrypto.js";
import type * as _services_cache_cacheMetrics from "../_services/cache/cacheMetrics.js";
import type * as _services_cache_cachedAgent from "../_services/cache/cachedAgent.js";
import type * as _services_extraction_AcademicLoaderService from "../_services/extraction/AcademicLoaderService.js";
import type * as _services_extraction_AudioTranscriptionService from "../_services/extraction/AudioTranscriptionService.js";
import type * as _services_extraction_BibliographyParserService from "../_services/extraction/BibliographyParserService.js";
import type * as _services_extraction_DoiResolverService from "../_services/extraction/DoiResolverService.js";
import type * as _services_extraction_MistralOCRService from "../_services/extraction/MistralOCRService.js";
import type * as _services_extraction_WebLoaderService from "../_services/extraction/WebLoaderService.js";
import type * as _services_extractors from "../_services/extractors.js";
import type * as _services_grading_WrittenQuestionsGradingService from "../_services/grading/WrittenQuestionsGradingService.js";
import type * as _services_processing_DocumentMetadataExtractor from "../_services/processing/DocumentMetadataExtractor.js";
import type * as _services_processing_EmbeddingServiceClient from "../_services/processing/EmbeddingServiceClient.js";
import type * as _services_processing_StructuralChunker from "../_services/processing/StructuralChunker.js";
import type * as _services_processing_TextSplitterService from "../_services/processing/TextSplitterService.js";
import type * as _services_search_AcademicSearchService from "../_services/search/AcademicSearchService.js";
import type * as _services_search_DiscoveryService from "../_services/search/DiscoveryService.js";
import type * as _services_search_TavilySearchService from "../_services/search/TavilySearchService.js";
import type * as _shared_mathMarkdown from "../_shared/mathMarkdown.js";
import type * as _utils_CitationEngine from "../_utils/CitationEngine.js";
import type * as auth from "../auth.js";
import type * as billing_actions from "../billing/actions.js";
import type * as billing_index from "../billing/index.js";
import type * as billing_webhook from "../billing/webhook.js";
import type * as chat__researchExecuteImpl from "../chat/_researchExecuteImpl.js";
import type * as chat__researchPlan from "../chat/_researchPlan.js";
import type * as chat__streamBuffer from "../chat/_streamBuffer.js";
import type * as chat__streamChatResponse from "../chat/_streamChatResponse.js";
import type * as chat__streamResearch from "../chat/_streamResearch.js";
import type * as chat__streamSearch from "../chat/_streamSearch.js";
import type * as chat__streamSources from "../chat/_streamSources.js";
import type * as chat_actions from "../chat/actions.js";
import type * as chat_conversations from "../chat/conversations.js";
import type * as chat_index from "../chat/index.js";
import type * as chat_messages from "../chat/messages.js";
import type * as chat_sourceSuggestions from "../chat/sourceSuggestions.js";
import type * as chat_stream from "../chat/stream.js";
import type * as chat_voiceTranscription from "../chat/voiceTranscription.js";
import type * as chat_voiceTranscriptionAccess from "../chat/voiceTranscriptionAccess.js";
import type * as documents_bulkUpload from "../documents/bulkUpload.js";
import type * as documents_chunks from "../documents/chunks.js";
import type * as documents_embeddingJob from "../documents/embeddingJob.js";
import type * as documents_embeddings from "../documents/embeddings.js";
import type * as documents_getExistingPapers from "../documents/getExistingPapers.js";
import type * as documents_index from "../documents/index.js";
import type * as documents_internal from "../documents/internal.js";
import type * as documents_paperRecord from "../documents/paperRecord.js";
import type * as documents_parseBibliography from "../documents/parseBibliography.js";
import type * as documents_refreshRemote from "../documents/refreshRemote.js";
import type * as documents_resolveDoi from "../documents/resolveDoi.js";
import type * as documents_sourceGuide from "../documents/sourceGuide.js";
import type * as e2e_cleanupNotebooks from "../e2e/cleanupNotebooks.js";
import type * as e2e_seedFlashcards from "../e2e/seedFlashcards.js";
import type * as eval__gate from "../eval/_gate.js";
import type * as eval__studioRowCreators from "../eval/_studioRowCreators.js";
import type * as eval_chatEvalAction from "../eval/chatEvalAction.js";
import type * as eval_literatureReviewEvalAction from "../eval/literatureReviewEvalAction.js";
import type * as eval_researchEvalAction from "../eval/researchEvalAction.js";
import type * as eval_studioEvalAction from "../eval/studioEvalAction.js";
import type * as folders_index from "../folders/index.js";
import type * as googleDrive from "../googleDrive.js";
import type * as http from "../http.js";
import type * as literatureReview_batchSizes from "../literatureReview/batchSizes.js";
import type * as literatureReview_db from "../literatureReview/db.js";
import type * as literatureReview_llmTuning from "../literatureReview/llmTuning.js";
import type * as literatureReview_rankedPapersSnapshot from "../literatureReview/rankedPapersSnapshot.js";
import type * as literatureReview_reportContext from "../literatureReview/reportContext.js";
import type * as literatureReview_titles from "../literatureReview/titles.js";
import type * as literatureReview_workflowProvenance from "../literatureReview/workflowProvenance.js";
import type * as literatureReview_workflowSteps from "../literatureReview/workflowSteps.js";
import type * as notebooks__forkNotebook from "../notebooks/_forkNotebook.js";
import type * as notebooks_index from "../notebooks/index.js";
import type * as notebooks_sharing from "../notebooks/sharing.js";
import type * as notes_index from "../notes/index.js";
import type * as notes_userNotes from "../notes/userNotes.js";
import type * as onboarding_constants from "../onboarding/constants.js";
import type * as onboarding_mutations from "../onboarding/mutations.js";
import type * as onboarding_progress from "../onboarding/progress.js";
import type * as onboarding_state from "../onboarding/state.js";
import type * as push_index from "../push/index.js";
import type * as research_artifacts from "../research/artifacts.js";
import type * as research_index from "../research/index.js";
import type * as research_mapEvidenceForDb from "../research/mapEvidenceForDb.js";
import type * as research_reportSections from "../research/reportSections.js";
import type * as research_resolveResearchTitle from "../research/resolveResearchTitle.js";
import type * as research_titles from "../research/titles.js";
import type * as research_workflowSteps from "../research/workflowSteps.js";
import type * as server from "../server.js";
import type * as storage_ChatHistoryService from "../storage/ChatHistoryService.js";
import type * as storage_ConvexStorageService from "../storage/ConvexStorageService.js";
import type * as storage_VectorStoreService from "../storage/VectorStoreService.js";
import type * as studio__job_collapseStringOutputsByTokens from "../studio/_job/collapseStringOutputsByTokens.js";
import type * as studio__job_invokeStudioLlm from "../studio/_job/invokeStudioLlm.js";
import type * as studio_audio_audioJobPhases from "../studio/audio/audioJobPhases.js";
import type * as studio_audio_fixAudioUrl from "../studio/audio/fixAudioUrl.js";
import type * as studio_audio_index from "../studio/audio/index.js";
import type * as studio_audio_job from "../studio/audio/job.js";
import type * as studio_flashcards_flashcardJobPhases from "../studio/flashcards/flashcardJobPhases.js";
import type * as studio_flashcards_index from "../studio/flashcards/index.js";
import type * as studio_flashcards_job from "../studio/flashcards/job.js";
import type * as studio_infographic_generate from "../studio/infographic/generate.js";
import type * as studio_infographic_index from "../studio/infographic/index.js";
import type * as studio_infographic_prompts from "../studio/infographic/prompts.js";
import type * as studio_jobMutations_audio from "../studio/jobMutations/audio.js";
import type * as studio_jobMutations_documents from "../studio/jobMutations/documents.js";
import type * as studio_jobMutations_flashcards from "../studio/jobMutations/flashcards.js";
import type * as studio_jobMutations_infographics from "../studio/jobMutations/infographics.js";
import type * as studio_jobMutations_jobErrorUtils from "../studio/jobMutations/jobErrorUtils.js";
import type * as studio_jobMutations_mindmaps from "../studio/jobMutations/mindmaps.js";
import type * as studio_jobMutations_quizzes from "../studio/jobMutations/quizzes.js";
import type * as studio_jobMutations_reports from "../studio/jobMutations/reports.js";
import type * as studio_jobMutations_spreadsheets from "../studio/jobMutations/spreadsheets.js";
import type * as studio_jobMutations_writtenQuestions from "../studio/jobMutations/writtenQuestions.js";
import type * as studio_literature_tables_index from "../studio/literature_tables/index.js";
import type * as studio_mindmaps_index from "../studio/mindmaps/index.js";
import type * as studio_mindmaps_job from "../studio/mindmaps/job.js";
import type * as studio_mindmaps_mindmapJobPhases from "../studio/mindmaps/mindmapJobPhases.js";
import type * as studio_prompts_config from "../studio/prompts/config.js";
import type * as studio_prompts_index from "../studio/prompts/index.js";
import type * as studio_quizzes_index from "../studio/quizzes/index.js";
import type * as studio_quizzes_job from "../studio/quizzes/job.js";
import type * as studio_quizzes_quizJobPhases from "../studio/quizzes/quizJobPhases.js";
import type * as studio_reports_index from "../studio/reports/index.js";
import type * as studio_reports_job from "../studio/reports/job.js";
import type * as studio_reports_reportJobPhases from "../studio/reports/reportJobPhases.js";
import type * as studio_scheduling_flashcards from "../studio/scheduling/flashcards.js";
import type * as studio_scheduling_quizzes from "../studio/scheduling/quizzes.js";
import type * as studio_scheduling_reports from "../studio/scheduling/reports.js";
import type * as studio_scheduling_spreadsheets from "../studio/scheduling/spreadsheets.js";
import type * as studio_scheduling_writtenQuestions from "../studio/scheduling/writtenQuestions.js";
import type * as studio_spreadsheets_index from "../studio/spreadsheets/index.js";
import type * as studio_spreadsheets_job from "../studio/spreadsheets/job.js";
import type * as studio_spreadsheets_spreadsheetJobPhases from "../studio/spreadsheets/spreadsheetJobPhases.js";
import type * as studio_writtenQuestions_grading from "../studio/writtenQuestions/grading.js";
import type * as studio_writtenQuestions_index from "../studio/writtenQuestions/index.js";
import type * as studio_writtenQuestions_job from "../studio/writtenQuestions/job.js";
import type * as studio_writtenQuestions_writtenQuestionsJobPhases from "../studio/writtenQuestions/writtenQuestionsJobPhases.js";
import type * as userPreferences_index from "../userPreferences/index.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  ResendOTP: typeof ResendOTP;
  ResendOTPPasswordReset: typeof ResendOTPPasswordReset;
  "_agents/AudioOverviewGraph": typeof _agents_AudioOverviewGraph;
  "_agents/ChatAgent": typeof _agents_ChatAgent;
  "_agents/FlashcardGraph": typeof _agents_FlashcardGraph;
  "_agents/MindMapGraph": typeof _agents_MindMapGraph;
  "_agents/QuizGraph": typeof _agents_QuizGraph;
  "_agents/ReportGraph": typeof _agents_ReportGraph;
  "_agents/SpreadsheetGraph": typeof _agents_SpreadsheetGraph;
  "_agents/WrittenQuestionsGraph": typeof _agents_WrittenQuestionsGraph;
  "_agents/_shared/agent_graph_limits": typeof _agents__shared_agent_graph_limits;
  "_agents/_shared/cachedLlm": typeof _agents__shared_cachedLlm;
  "_agents/_shared/chunk_helper_factory": typeof _agents__shared_chunk_helper_factory;
  "_agents/_shared/chunk_operations": typeof _agents__shared_chunk_operations;
  "_agents/_shared/citationExtract": typeof _agents__shared_citationExtract;
  "_agents/_shared/concurrency": typeof _agents__shared_concurrency;
  "_agents/_shared/graph_builder": typeof _agents__shared_graph_builder;
  "_agents/_shared/index": typeof _agents__shared_index;
  "_agents/_shared/jobHelpers": typeof _agents__shared_jobHelpers;
  "_agents/_shared/languageInstruction": typeof _agents__shared_languageInstruction;
  "_agents/_shared/llm_factory": typeof _agents__shared_llm_factory;
  "_agents/_shared/logging": typeof _agents__shared_logging;
  "_agents/_shared/markdownMathPrompt": typeof _agents__shared_markdownMathPrompt;
  "_agents/_shared/node_builder": typeof _agents__shared_node_builder;
  "_agents/_shared/progress": typeof _agents__shared_progress;
  "_agents/_shared/retry": typeof _agents__shared_retry;
  "_agents/_shared/sanitization": typeof _agents__shared_sanitization;
  "_agents/_shared/stateUpdateHelpers": typeof _agents__shared_stateUpdateHelpers;
  "_agents/_shared/state_cleanup": typeof _agents__shared_state_cleanup;
  "_agents/_shared/state_factory": typeof _agents__shared_state_factory;
  "_agents/_shared/timeout": typeof _agents__shared_timeout;
  "_agents/_shared/tokenizer": typeof _agents__shared_tokenizer;
  "_agents/_shared/topic_extraction": typeof _agents__shared_topic_extraction;
  "_agents/_shared/validation": typeof _agents__shared_validation;
  "_agents/audio_overview/AudioOverviewGraph": typeof _agents_audio_overview_AudioOverviewGraph;
  "_agents/audio_overview/chunkHelpers": typeof _agents_audio_overview_chunkHelpers;
  "_agents/audio_overview/config": typeof _agents_audio_overview_config;
  "_agents/audio_overview/nodeCollapse": typeof _agents_audio_overview_nodeCollapse;
  "_agents/audio_overview/nodeExtractBeats": typeof _agents_audio_overview_nodeExtractBeats;
  "_agents/audio_overview/nodeSynthesizeAudio": typeof _agents_audio_overview_nodeSynthesizeAudio;
  "_agents/audio_overview/nodeWriteScript": typeof _agents_audio_overview_nodeWriteScript;
  "_agents/audio_overview/prompts": typeof _agents_audio_overview_prompts;
  "_agents/audio_overview/scriptParsing": typeof _agents_audio_overview_scriptParsing;
  "_agents/audio_overview/state": typeof _agents_audio_overview_state;
  "_agents/audio_overview/voices": typeof _agents_audio_overview_voices;
  "_agents/chat/ChatAgent": typeof _agents_chat_ChatAgent;
  "_agents/chat/chatConfig": typeof _agents_chat_chatConfig;
  "_agents/chat/chatHistoryBudget": typeof _agents_chat_chatHistoryBudget;
  "_agents/chat/chatRouter": typeof _agents_chat_chatRouter;
  "_agents/chat/chat_llm_grounding": typeof _agents_chat_chat_llm_grounding;
  "_agents/chat/chat_llm_prompts": typeof _agents_chat_chat_llm_prompts;
  "_agents/chat/chat_llm_types": typeof _agents_chat_chat_llm_types;
  "_agents/chat/chat_retrieval_subqueries": typeof _agents_chat_chat_retrieval_subqueries;
  "_agents/chat/chunkContext": typeof _agents_chat_chunkContext;
  "_agents/chat/grounding_validator": typeof _agents_chat_grounding_validator;
  "_agents/chat/hybrid_search": typeof _agents_chat_hybrid_search;
  "_agents/chat/llm_wrapper": typeof _agents_chat_llm_wrapper;
  "_agents/chat/queryExpansion": typeof _agents_chat_queryExpansion;
  "_agents/chat/rerankCache": typeof _agents_chat_rerankCache;
  "_agents/chat/searchQueryRefiner": typeof _agents_chat_searchQueryRefiner;
  "_agents/chat/sourceSuggestions": typeof _agents_chat_sourceSuggestions;
  "_agents/chat/streamSlice": typeof _agents_chat_streamSlice;
  "_agents/chat/types": typeof _agents_chat_types;
  "_agents/chat/vector_search": typeof _agents_chat_vector_search;
  "_agents/chat/withTimeout": typeof _agents_chat_withTimeout;
  "_agents/flashcard/FlashcardGraph": typeof _agents_flashcard_FlashcardGraph;
  "_agents/flashcard/chunkHelpers": typeof _agents_flashcard_chunkHelpers;
  "_agents/flashcard/collapseReduceLlm": typeof _agents_flashcard_collapseReduceLlm;
  "_agents/flashcard/config": typeof _agents_flashcard_config;
  "_agents/flashcard/flashcardHeuristics": typeof _agents_flashcard_flashcardHeuristics;
  "_agents/flashcard/formatFlashcards": typeof _agents_flashcard_formatFlashcards;
  "_agents/flashcard/nodeCollapse": typeof _agents_flashcard_nodeCollapse;
  "_agents/flashcard/nodeMap": typeof _agents_flashcard_nodeMap;
  "_agents/flashcard/nodeReduce": typeof _agents_flashcard_nodeReduce;
  "_agents/flashcard/nodeSplit": typeof _agents_flashcard_nodeSplit;
  "_agents/flashcard/prompts": typeof _agents_flashcard_prompts;
  "_agents/flashcard/routing": typeof _agents_flashcard_routing;
  "_agents/flashcard/state": typeof _agents_flashcard_state;
  "_agents/flashcard/structuredLlm": typeof _agents_flashcard_structuredLlm;
  "_agents/flashcard/textCleanup": typeof _agents_flashcard_textCleanup;
  "_agents/literature_review/LiteratureReviewGraph": typeof _agents_literature_review_LiteratureReviewGraph;
  "_agents/literature_review/planReviewColumns": typeof _agents_literature_review_planReviewColumns;
  "_agents/literature_review/prompts": typeof _agents_literature_review_prompts;
  "_agents/literature_review/state": typeof _agents_literature_review_state;
  "_agents/literature_review/types": typeof _agents_literature_review_types;
  "_agents/mindmap/MindMapGraph": typeof _agents_mindmap_MindMapGraph;
  "_agents/mindmap/chunkHelpers": typeof _agents_mindmap_chunkHelpers;
  "_agents/mindmap/config": typeof _agents_mindmap_config;
  "_agents/mindmap/fallbacks": typeof _agents_mindmap_fallbacks;
  "_agents/mindmap/nodeMap": typeof _agents_mindmap_nodeMap;
  "_agents/mindmap/nodeReduce": typeof _agents_mindmap_nodeReduce;
  "_agents/mindmap/parsing": typeof _agents_mindmap_parsing;
  "_agents/mindmap/prompts": typeof _agents_mindmap_prompts;
  "_agents/mindmap/routing": typeof _agents_mindmap_routing;
  "_agents/mindmap/state": typeof _agents_mindmap_state;
  "_agents/mindmap/structuredLlm": typeof _agents_mindmap_structuredLlm;
  "_agents/quiz/QuizGraph": typeof _agents_quiz_QuizGraph;
  "_agents/quiz/chunkHelpers": typeof _agents_quiz_chunkHelpers;
  "_agents/quiz/config": typeof _agents_quiz_config;
  "_agents/quiz/nodeCollapse": typeof _agents_quiz_nodeCollapse;
  "_agents/quiz/nodeMap": typeof _agents_quiz_nodeMap;
  "_agents/quiz/nodeReduce": typeof _agents_quiz_nodeReduce;
  "_agents/quiz/nodeSplit": typeof _agents_quiz_nodeSplit;
  "_agents/quiz/optionLabels": typeof _agents_quiz_optionLabels;
  "_agents/quiz/postprocess": typeof _agents_quiz_postprocess;
  "_agents/quiz/prompts": typeof _agents_quiz_prompts;
  "_agents/quiz/quizHeuristics": typeof _agents_quiz_quizHeuristics;
  "_agents/quiz/routing": typeof _agents_quiz_routing;
  "_agents/quiz/state": typeof _agents_quiz_state;
  "_agents/quiz/structuredLlm": typeof _agents_quiz_structuredLlm;
  "_agents/report/ReportGraph": typeof _agents_report_ReportGraph;
  "_agents/report/chunkHelpers": typeof _agents_report_chunkHelpers;
  "_agents/report/config": typeof _agents_report_config;
  "_agents/report/inputValidation": typeof _agents_report_inputValidation;
  "_agents/report/invokeHelpers": typeof _agents_report_invokeHelpers;
  "_agents/report/nodeCollapse": typeof _agents_report_nodeCollapse;
  "_agents/report/nodeMap": typeof _agents_report_nodeMap;
  "_agents/report/nodeMerge": typeof _agents_report_nodeMerge;
  "_agents/report/nodeReduce": typeof _agents_report_nodeReduce;
  "_agents/report/nodes": typeof _agents_report_nodes;
  "_agents/report/prompts": typeof _agents_report_prompts;
  "_agents/report/routing": typeof _agents_report_routing;
  "_agents/report/state": typeof _agents_report_state;
  "_agents/report/structuredLlm": typeof _agents_report_structuredLlm;
  "_agents/report/topicAnalysis": typeof _agents_report_topicAnalysis;
  "_agents/research/DeepResearchGraph": typeof _agents_research_DeepResearchGraph;
  "_agents/research/graph": typeof _agents_research_graph;
  "_agents/research/index": typeof _agents_research_index;
  "_agents/research/nodes": typeof _agents_research_nodes;
  "_agents/research/prompts": typeof _agents_research_prompts;
  "_agents/research/state": typeof _agents_research_state;
  "_agents/research/steps": typeof _agents_research_steps;
  "_agents/research/types": typeof _agents_research_types;
  "_agents/spreadsheet/SpreadsheetGraph": typeof _agents_spreadsheet_SpreadsheetGraph;
  "_agents/spreadsheet/chunkHelpers": typeof _agents_spreadsheet_chunkHelpers;
  "_agents/spreadsheet/config": typeof _agents_spreadsheet_config;
  "_agents/spreadsheet/csvHelpers": typeof _agents_spreadsheet_csvHelpers;
  "_agents/spreadsheet/inputValidation": typeof _agents_spreadsheet_inputValidation;
  "_agents/spreadsheet/nodeCollapse": typeof _agents_spreadsheet_nodeCollapse;
  "_agents/spreadsheet/nodeMap": typeof _agents_spreadsheet_nodeMap;
  "_agents/spreadsheet/nodeMerge": typeof _agents_spreadsheet_nodeMerge;
  "_agents/spreadsheet/nodeReduce": typeof _agents_spreadsheet_nodeReduce;
  "_agents/spreadsheet/prompts": typeof _agents_spreadsheet_prompts;
  "_agents/spreadsheet/routing": typeof _agents_spreadsheet_routing;
  "_agents/spreadsheet/state": typeof _agents_spreadsheet_state;
  "_agents/written_questions/WrittenQuestionsGraph": typeof _agents_written_questions_WrittenQuestionsGraph;
  "_agents/written_questions/chunkHelpers": typeof _agents_written_questions_chunkHelpers;
  "_agents/written_questions/config": typeof _agents_written_questions_config;
  "_agents/written_questions/nodeCollapse": typeof _agents_written_questions_nodeCollapse;
  "_agents/written_questions/nodeMap": typeof _agents_written_questions_nodeMap;
  "_agents/written_questions/nodeReduce": typeof _agents_written_questions_nodeReduce;
  "_agents/written_questions/nodeSplit": typeof _agents_written_questions_nodeSplit;
  "_agents/written_questions/postprocess": typeof _agents_written_questions_postprocess;
  "_agents/written_questions/prompts": typeof _agents_written_questions_prompts;
  "_agents/written_questions/questionHeuristics": typeof _agents_written_questions_questionHeuristics;
  "_agents/written_questions/routing": typeof _agents_written_questions_routing;
  "_agents/written_questions/state": typeof _agents_written_questions_state;
  "_agents/written_questions/structuredLlm": typeof _agents_written_questions_structuredLlm;
  "_lib/arxivThrottle": typeof _lib_arxivThrottle;
  "_lib/conversationAccess": typeof _lib_conversationAccess;
  "_lib/e5Embedding": typeof _lib_e5Embedding;
  "_lib/env": typeof _lib_env;
  "_lib/errors": typeof _lib_errors;
  "_lib/externalProviderCooldowns": typeof _lib_externalProviderCooldowns;
  "_lib/googleDriveDownload": typeof _lib_googleDriveDownload;
  "_lib/limits": typeof _lib_limits;
  "_lib/logging/serviceLogger": typeof _lib_logging_serviceLogger;
  "_lib/notebookAccess": typeof _lib_notebookAccess;
  "_lib/queryCaps": typeof _lib_queryCaps;
  "_lib/rateLimits": typeof _lib_rateLimits;
  "_lib/resendSendError": typeof _lib_resendSendError;
  "_lib/resolveSmartModel": typeof _lib_resolveSmartModel;
  "_lib/semanticScholarThrottle": typeof _lib_semanticScholarThrottle;
  "_lib/serviceErrors": typeof _lib_serviceErrors;
  "_lib/shareToken": typeof _lib_shareToken;
  "_lib/srsScheduling": typeof _lib_srsScheduling;
  "_lib/utils/urlValidation": typeof _lib_utils_urlValidation;
  "_migration/index": typeof _migration_index;
  "_migration/reembedBatchesWorker": typeof _migration_reembedBatchesWorker;
  "_migration/reembedChunks": typeof _migration_reembedChunks;
  "_migration/removeSlidePrompts": typeof _migration_removeSlidePrompts;
  "_model/audioOverviews": typeof _model_audioOverviews;
  "_model/conversations": typeof _model_conversations;
  "_model/documents": typeof _model_documents;
  "_model/flashcards": typeof _model_flashcards;
  "_model/folders": typeof _model_folders;
  "_model/infographics": typeof _model_infographics;
  "_model/literatureReviewSearchOptions": typeof _model_literatureReviewSearchOptions;
  "_model/mindmaps": typeof _model_mindmaps;
  "_model/notebooks": typeof _model_notebooks;
  "_model/notes": typeof _model_notes;
  "_model/quizzes": typeof _model_quizzes;
  "_model/reports": typeof _model_reports;
  "_model/spreadsheets": typeof _model_spreadsheets;
  "_model/writtenQuestions": typeof _model_writtenQuestions;
  "_services/ai/embeddings": typeof _services_ai_embeddings;
  "_services/ai/mp3": typeof _services_ai_mp3;
  "_services/ai/titleGenerator": typeof _services_ai_titleGenerator;
  "_services/ai/togetherClient": typeof _services_ai_togetherClient;
  "_services/ai/togetherImages": typeof _services_ai_togetherImages;
  "_services/ai/togetherTts": typeof _services_ai_togetherTts;
  "_services/ai/wav": typeof _services_ai_wav;
  "_services/cache/cache": typeof _services_cache_cache;
  "_services/cache/cacheCrypto": typeof _services_cache_cacheCrypto;
  "_services/cache/cacheMetrics": typeof _services_cache_cacheMetrics;
  "_services/cache/cachedAgent": typeof _services_cache_cachedAgent;
  "_services/extraction/AcademicLoaderService": typeof _services_extraction_AcademicLoaderService;
  "_services/extraction/AudioTranscriptionService": typeof _services_extraction_AudioTranscriptionService;
  "_services/extraction/BibliographyParserService": typeof _services_extraction_BibliographyParserService;
  "_services/extraction/DoiResolverService": typeof _services_extraction_DoiResolverService;
  "_services/extraction/MistralOCRService": typeof _services_extraction_MistralOCRService;
  "_services/extraction/WebLoaderService": typeof _services_extraction_WebLoaderService;
  "_services/extractors": typeof _services_extractors;
  "_services/grading/WrittenQuestionsGradingService": typeof _services_grading_WrittenQuestionsGradingService;
  "_services/processing/DocumentMetadataExtractor": typeof _services_processing_DocumentMetadataExtractor;
  "_services/processing/EmbeddingServiceClient": typeof _services_processing_EmbeddingServiceClient;
  "_services/processing/StructuralChunker": typeof _services_processing_StructuralChunker;
  "_services/processing/TextSplitterService": typeof _services_processing_TextSplitterService;
  "_services/search/AcademicSearchService": typeof _services_search_AcademicSearchService;
  "_services/search/DiscoveryService": typeof _services_search_DiscoveryService;
  "_services/search/TavilySearchService": typeof _services_search_TavilySearchService;
  "_shared/mathMarkdown": typeof _shared_mathMarkdown;
  "_utils/CitationEngine": typeof _utils_CitationEngine;
  auth: typeof auth;
  "billing/actions": typeof billing_actions;
  "billing/index": typeof billing_index;
  "billing/webhook": typeof billing_webhook;
  "chat/_researchExecuteImpl": typeof chat__researchExecuteImpl;
  "chat/_researchPlan": typeof chat__researchPlan;
  "chat/_streamBuffer": typeof chat__streamBuffer;
  "chat/_streamChatResponse": typeof chat__streamChatResponse;
  "chat/_streamResearch": typeof chat__streamResearch;
  "chat/_streamSearch": typeof chat__streamSearch;
  "chat/_streamSources": typeof chat__streamSources;
  "chat/actions": typeof chat_actions;
  "chat/conversations": typeof chat_conversations;
  "chat/index": typeof chat_index;
  "chat/messages": typeof chat_messages;
  "chat/sourceSuggestions": typeof chat_sourceSuggestions;
  "chat/stream": typeof chat_stream;
  "chat/voiceTranscription": typeof chat_voiceTranscription;
  "chat/voiceTranscriptionAccess": typeof chat_voiceTranscriptionAccess;
  "documents/bulkUpload": typeof documents_bulkUpload;
  "documents/chunks": typeof documents_chunks;
  "documents/embeddingJob": typeof documents_embeddingJob;
  "documents/embeddings": typeof documents_embeddings;
  "documents/getExistingPapers": typeof documents_getExistingPapers;
  "documents/index": typeof documents_index;
  "documents/internal": typeof documents_internal;
  "documents/paperRecord": typeof documents_paperRecord;
  "documents/parseBibliography": typeof documents_parseBibliography;
  "documents/refreshRemote": typeof documents_refreshRemote;
  "documents/resolveDoi": typeof documents_resolveDoi;
  "documents/sourceGuide": typeof documents_sourceGuide;
  "e2e/cleanupNotebooks": typeof e2e_cleanupNotebooks;
  "e2e/seedFlashcards": typeof e2e_seedFlashcards;
  "eval/_gate": typeof eval__gate;
  "eval/_studioRowCreators": typeof eval__studioRowCreators;
  "eval/chatEvalAction": typeof eval_chatEvalAction;
  "eval/literatureReviewEvalAction": typeof eval_literatureReviewEvalAction;
  "eval/researchEvalAction": typeof eval_researchEvalAction;
  "eval/studioEvalAction": typeof eval_studioEvalAction;
  "folders/index": typeof folders_index;
  googleDrive: typeof googleDrive;
  http: typeof http;
  "literatureReview/batchSizes": typeof literatureReview_batchSizes;
  "literatureReview/db": typeof literatureReview_db;
  "literatureReview/llmTuning": typeof literatureReview_llmTuning;
  "literatureReview/rankedPapersSnapshot": typeof literatureReview_rankedPapersSnapshot;
  "literatureReview/reportContext": typeof literatureReview_reportContext;
  "literatureReview/titles": typeof literatureReview_titles;
  "literatureReview/workflowProvenance": typeof literatureReview_workflowProvenance;
  "literatureReview/workflowSteps": typeof literatureReview_workflowSteps;
  "notebooks/_forkNotebook": typeof notebooks__forkNotebook;
  "notebooks/index": typeof notebooks_index;
  "notebooks/sharing": typeof notebooks_sharing;
  "notes/index": typeof notes_index;
  "notes/userNotes": typeof notes_userNotes;
  "onboarding/constants": typeof onboarding_constants;
  "onboarding/mutations": typeof onboarding_mutations;
  "onboarding/progress": typeof onboarding_progress;
  "onboarding/state": typeof onboarding_state;
  "push/index": typeof push_index;
  "research/artifacts": typeof research_artifacts;
  "research/index": typeof research_index;
  "research/mapEvidenceForDb": typeof research_mapEvidenceForDb;
  "research/reportSections": typeof research_reportSections;
  "research/resolveResearchTitle": typeof research_resolveResearchTitle;
  "research/titles": typeof research_titles;
  "research/workflowSteps": typeof research_workflowSteps;
  server: typeof server;
  "storage/ChatHistoryService": typeof storage_ChatHistoryService;
  "storage/ConvexStorageService": typeof storage_ConvexStorageService;
  "storage/VectorStoreService": typeof storage_VectorStoreService;
  "studio/_job/collapseStringOutputsByTokens": typeof studio__job_collapseStringOutputsByTokens;
  "studio/_job/invokeStudioLlm": typeof studio__job_invokeStudioLlm;
  "studio/audio/audioJobPhases": typeof studio_audio_audioJobPhases;
  "studio/audio/fixAudioUrl": typeof studio_audio_fixAudioUrl;
  "studio/audio/index": typeof studio_audio_index;
  "studio/audio/job": typeof studio_audio_job;
  "studio/flashcards/flashcardJobPhases": typeof studio_flashcards_flashcardJobPhases;
  "studio/flashcards/index": typeof studio_flashcards_index;
  "studio/flashcards/job": typeof studio_flashcards_job;
  "studio/infographic/generate": typeof studio_infographic_generate;
  "studio/infographic/index": typeof studio_infographic_index;
  "studio/infographic/prompts": typeof studio_infographic_prompts;
  "studio/jobMutations/audio": typeof studio_jobMutations_audio;
  "studio/jobMutations/documents": typeof studio_jobMutations_documents;
  "studio/jobMutations/flashcards": typeof studio_jobMutations_flashcards;
  "studio/jobMutations/infographics": typeof studio_jobMutations_infographics;
  "studio/jobMutations/jobErrorUtils": typeof studio_jobMutations_jobErrorUtils;
  "studio/jobMutations/mindmaps": typeof studio_jobMutations_mindmaps;
  "studio/jobMutations/quizzes": typeof studio_jobMutations_quizzes;
  "studio/jobMutations/reports": typeof studio_jobMutations_reports;
  "studio/jobMutations/spreadsheets": typeof studio_jobMutations_spreadsheets;
  "studio/jobMutations/writtenQuestions": typeof studio_jobMutations_writtenQuestions;
  "studio/literature_tables/index": typeof studio_literature_tables_index;
  "studio/mindmaps/index": typeof studio_mindmaps_index;
  "studio/mindmaps/job": typeof studio_mindmaps_job;
  "studio/mindmaps/mindmapJobPhases": typeof studio_mindmaps_mindmapJobPhases;
  "studio/prompts/config": typeof studio_prompts_config;
  "studio/prompts/index": typeof studio_prompts_index;
  "studio/quizzes/index": typeof studio_quizzes_index;
  "studio/quizzes/job": typeof studio_quizzes_job;
  "studio/quizzes/quizJobPhases": typeof studio_quizzes_quizJobPhases;
  "studio/reports/index": typeof studio_reports_index;
  "studio/reports/job": typeof studio_reports_job;
  "studio/reports/reportJobPhases": typeof studio_reports_reportJobPhases;
  "studio/scheduling/flashcards": typeof studio_scheduling_flashcards;
  "studio/scheduling/quizzes": typeof studio_scheduling_quizzes;
  "studio/scheduling/reports": typeof studio_scheduling_reports;
  "studio/scheduling/spreadsheets": typeof studio_scheduling_spreadsheets;
  "studio/scheduling/writtenQuestions": typeof studio_scheduling_writtenQuestions;
  "studio/spreadsheets/index": typeof studio_spreadsheets_index;
  "studio/spreadsheets/job": typeof studio_spreadsheets_job;
  "studio/spreadsheets/spreadsheetJobPhases": typeof studio_spreadsheets_spreadsheetJobPhases;
  "studio/writtenQuestions/grading": typeof studio_writtenQuestions_grading;
  "studio/writtenQuestions/index": typeof studio_writtenQuestions_index;
  "studio/writtenQuestions/job": typeof studio_writtenQuestions_job;
  "studio/writtenQuestions/writtenQuestionsJobPhases": typeof studio_writtenQuestions_writtenQuestionsJobPhases;
  "userPreferences/index": typeof userPreferences_index;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  stripe: import("@convex-dev/stripe/_generated/component.js").ComponentApi<"stripe">;
  persistentTextStreaming: import("@convex-dev/persistent-text-streaming/_generated/component.js").ComponentApi<"persistentTextStreaming">;
  actionCache: import("@convex-dev/action-cache/_generated/component.js").ComponentApi<"actionCache">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
};
