"use node";

import { env } from "../../_lib/env.js";

const QUIZ_CONFIG = {
  MAP_CHUNK_SIZE_TOKENS: parseInt(env.QUIZ_MAP_CHUNK_TOKENS, 10),
  REDUCE_CHUNK_SIZE_TOKENS: parseInt(env.QUIZ_REDUCE_CHUNK_TOKENS, 10),
  MIN_QUESTIONS_PER_CHUNK: parseInt(env.QUIZ_MIN_QUESTIONS_PER_CHUNK, 10),
  MAX_QUESTIONS_PER_CHUNK: parseInt(env.QUIZ_MAX_QUESTIONS_PER_CHUNK, 10),
  MIN_CHUNKS: parseInt(env.QUIZ_MIN_CHUNKS, 10),
  MAP_MAX_TOKENS: parseInt(env.QUIZ_MAX_TOKENS, 10),
  MAP_TIMEOUT_MS: parseInt(env.QUIZ_MAP_TIMEOUT_MS, 10),
  REDUCE_TIMEOUT_MS: parseInt(env.QUIZ_REDUCE_TIMEOUT_MS, 10),
  REDUCE_MAX_TOKENS: parseInt(env.QUIZ_REDUCE_MAX_TOKENS, 10),
  EXPAND_MAX_TOKENS: parseInt(env.QUIZ_EXPAND_MAX_TOKENS, 10),
  EXPAND_CONCURRENCY: parseInt(env.QUIZ_EXPAND_CONCURRENCY, 10),
  MAX_COLLAPSE_DEPTH: 5,
} as const;

export const GRAPH_CONFIG = {
  ...QUIZ_CONFIG,
} as const;
