"use node"

import { env } from '../../_lib/env.js';

export const GRAPH_CONFIG = {
  MAP_CHUNK_SIZE_TOKENS: parseInt(env.REPORT_MAP_CHUNK_TOKENS || '5000', 10),
  REDUCE_CHUNK_SIZE_TOKENS: parseInt(env.REPORT_REDUCE_CHUNK_TOKENS || '15000', 10),
  MAP_TIMEOUT_MS: parseInt(env.REPORT_MAP_TIMEOUT_MS, 10),
  REDUCE_TIMEOUT_MS: parseInt(env.REPORT_REDUCE_TIMEOUT_MS, 10),
} as const;

export const PROCESSING_CONFIG = {
  MIN_CHUNK_LENGTH: 50,
  MAX_CHUNK_LENGTH: 50000,
  COLLAPSE_BUFFER_RATIO: 0.8,
  PREVIEW_LENGTH: 100,
  HASH_START_LENGTH: 50,
  HASH_END_LENGTH: 20,
  OUTPUT_PREVIEW_LENGTH: 300,
  TOPIC_PREVIEW_LENGTH: 150,
  LOG_PREVIEW_LENGTH: 500,
  MAX_TOPICS_PER_CHUNK: 5,
  TOKEN_ESTIMATION_RATIO: 3,
  TOPIC_CACHE_SIZE: 100,
  TOPIC_CACHE_KEY_LENGTH: 200,
  MAX_RETRY_ATTEMPTS: 3,
  RETRY_BACKOFF_MS: 1000,
  MAX_PROMPT_LENGTH: 5000,
  PER_CHUNK_TIMEOUT_MS: 180000,
} as const;
