/**
 * Environment variables for Convex functions
 * Centralized config to avoid circular dependencies
 */

export const env = {
  // OpenAI
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",

  // Together AI
  TOGETHER_AI_API_KEY: process.env.TOGETHER_AI_API_KEY || "",
  FAST_LLM: process.env.FAST_LLM || "openai/gpt-oss-120b",
  SMART_LLM: process.env.SMART_LLM || "openai/gpt-oss-120b",

  // Tavily (web search)
  TAVILY_API_KEY: process.env.TAVILY_API_KEY || "",

  // OpenAlex (academic papers)
  OPENALEX_BASE_URL: process.env.OPENALEX_BASE_URL || "https://api.openalex.org",

  // Mistral (OCR)
  MISTRAL_API_KEY: process.env.MISTRAL_API_KEY || "",

  // LangSmith (tracing)
  LANGSMITH_API_KEY: process.env.LANGSMITH_API_KEY || "",
  LANGSMITH_PROJECT: process.env.LANGSMITH_PROJECT || "",
  LANGSMITH_ENDPOINT: process.env.LANGSMITH_ENDPOINT || "",
  LANGSMITH_TRACING: process.env.LANGSMITH_TRACING || "false",

  // LangChain env vars
  LANGCHAIN_API_KEY: process.env.LANGCHAIN_API_KEY || "",
  LANGCHAIN_PROJECT: process.env.LANGCHAIN_PROJECT || "",
  LANGCHAIN_TRACING_V2: process.env.LANGCHAIN_TRACING_V2 || "false",

  // Supadata
  SUPADATA_API_KEY: process.env.SUPADATA_API_KEY || "",

  // Audio Overview
  AUDIO_MAP_CHUNK_TOKENS: process.env.AUDIO_MAP_CHUNK_TOKENS || "20000",
  AUDIO_REDUCE_CHUNK_TOKENS: process.env.AUDIO_REDUCE_CHUNK_TOKENS || "40000",
  AUDIO_MAP_TIMEOUT_MS: process.env.AUDIO_MAP_TIMEOUT_MS || "300000",
  AUDIO_REDUCE_TIMEOUT_MS: process.env.AUDIO_REDUCE_TIMEOUT_MS || "300000",
  /** Max completion tokens for script-writing (reduce); too low yields finish_reason=length and empty content */
  AUDIO_REDUCE_MAX_OUTPUT_TOKENS: process.env.AUDIO_REDUCE_MAX_OUTPUT_TOKENS || "16384",
  AUDIO_TTS_TIMEOUT_MS: process.env.AUDIO_TTS_TIMEOUT_MS || "300000",
  /** Together AI TTS model (e.g. Kokoro). */
  AUDIO_TTS_MODEL: process.env.AUDIO_TTS_MODEL || "hexgrad/Kokoro-82M",
  /** Kokoro voice IDs — see Together text-to-speech docs. */
  AUDIO_VOICE_HOST_A: process.env.AUDIO_VOICE_HOST_A || "af_sky",
  AUDIO_VOICE_HOST_B: process.env.AUDIO_VOICE_HOST_B || "am_echo",

  // Flashcards
  FLASHCARD_MAP_CHUNK_TOKENS: process.env.FLASHCARD_MAP_CHUNK_TOKENS || "5000",
  FLASHCARD_REDUCE_CHUNK_TOKENS: process.env.FLASHCARD_REDUCE_CHUNK_TOKENS || "10000",
  FLASHCARD_MAP_TIMEOUT_MS: process.env.FLASHCARD_MAP_TIMEOUT_MS || "180000",
  FLASHCARD_REDUCE_TIMEOUT_MS: process.env.FLASHCARD_REDUCE_TIMEOUT_MS || "240000",
  FLASHCARD_REDUCE_MAX_TOKENS: process.env.FLASHCARD_REDUCE_MAX_TOKENS || "32000",

  // Quiz
  QUIZ_MAP_CHUNK_TOKENS: process.env.QUIZ_MAP_CHUNK_TOKENS || "5000",
  QUIZ_REDUCE_CHUNK_TOKENS: process.env.QUIZ_REDUCE_CHUNK_TOKENS || "10000",
  QUIZ_MAP_TIMEOUT_MS: process.env.QUIZ_MAP_TIMEOUT_MS || "400000",
  QUIZ_REDUCE_TIMEOUT_MS: process.env.QUIZ_REDUCE_TIMEOUT_MS || "400000",
  QUIZ_MIN_QUESTIONS_PER_CHUNK: process.env.QUIZ_MIN_QUESTIONS_PER_CHUNK || "2",
  QUIZ_MAX_QUESTIONS_PER_CHUNK: process.env.QUIZ_MAX_QUESTIONS_PER_CHUNK || "20",
  QUIZ_MIN_CHUNKS: process.env.QUIZ_MIN_CHUNKS || "2",
  QUIZ_MAX_TOKENS: process.env.QUIZ_MAX_TOKENS || "8000",
  QUIZ_REDUCE_MAX_TOKENS: process.env.QUIZ_REDUCE_MAX_TOKENS || "24000",
  QUIZ_EXPAND_MAX_TOKENS: process.env.QUIZ_EXPAND_MAX_TOKENS || "4096",
  QUIZ_EXPAND_CONCURRENCY: process.env.QUIZ_EXPAND_CONCURRENCY || "5",

  // Mindmap
  MINDMAP_MAP_CHUNK_TOKENS: process.env.MINDMAP_MAP_CHUNK_TOKENS || "5000",
  MINDMAP_REDUCE_CHUNK_TOKENS: process.env.MINDMAP_REDUCE_CHUNK_TOKENS || "10000",
  MINDMAP_MAP_TIMEOUT_MS: process.env.MINDMAP_MAP_TIMEOUT_MS || "300000",
  MINDMAP_REDUCE_TIMEOUT_MS: process.env.MINDMAP_REDUCE_TIMEOUT_MS || "300000",

  // Report
  REPORT_MAP_CHUNK_TOKENS: process.env.REPORT_MAP_CHUNK_TOKENS || "5000",
  REPORT_REDUCE_CHUNK_TOKENS: process.env.REPORT_REDUCE_CHUNK_TOKENS || "15000",
  REPORT_MAP_TIMEOUT_MS: process.env.REPORT_MAP_TIMEOUT_MS || "600000",
  REPORT_REDUCE_TIMEOUT_MS: process.env.REPORT_REDUCE_TIMEOUT_MS || "600000",
  REPORT_MAP_MAX_OUTPUT_TOKENS: process.env.REPORT_MAP_MAX_OUTPUT_TOKENS || "8192",
  REPORT_REDUCE_MAX_OUTPUT_TOKENS: process.env.REPORT_REDUCE_MAX_OUTPUT_TOKENS || "32000",
  REPORT_COLLAPSE_CONCURRENCY: process.env.REPORT_COLLAPSE_CONCURRENCY || "5",
  REPORT_MAX_TOKENS: process.env.REPORT_MAX_TOKENS || "64000",

  // Slides
  SLIDES_MAP_CHUNK_TOKENS: process.env.SLIDES_MAP_CHUNK_TOKENS || "3000",
  SLIDES_REDUCE_CHUNK_TOKENS: process.env.SLIDES_REDUCE_CHUNK_TOKENS || "12000",
  SLIDES_MIN_SLIDES_PER_CHUNK: process.env.SLIDES_MIN_SLIDES_PER_CHUNK || "1",
  SLIDES_MAX_SLIDES_PER_CHUNK: process.env.SLIDES_MAX_SLIDES_PER_CHUNK || "6",
  SLIDES_MAX_TOKENS: process.env.SLIDES_MAX_TOKENS || "8000",
  SLIDES_MAP_TIMEOUT_MS: process.env.SLIDES_MAP_TIMEOUT_MS || "180000",
  SLIDES_REDUCE_TIMEOUT_MS: process.env.SLIDES_REDUCE_TIMEOUT_MS || "240000",
  SLIDES_IMAGE_TIMEOUT_MS: process.env.SLIDES_IMAGE_TIMEOUT_MS || "60000",

  // Spreadsheet
  SPREADSHEET_MAP_CHUNK_TOKENS: process.env.SPREADSHEET_MAP_CHUNK_TOKENS || "5000",
  SPREADSHEET_REDUCE_CHUNK_TOKENS: process.env.SPREADSHEET_REDUCE_CHUNK_TOKENS || "15000",
  SPREADSHEET_MAP_MAX_OUTPUT_TOKENS: process.env.SPREADSHEET_MAP_MAX_OUTPUT_TOKENS || "8192",
  SPREADSHEET_REDUCE_MAX_OUTPUT_TOKENS: process.env.SPREADSHEET_REDUCE_MAX_OUTPUT_TOKENS || "32000",
  SPREADSHEET_COLLAPSE_CONCURRENCY: process.env.SPREADSHEET_COLLAPSE_CONCURRENCY || "5",
  SPREADSHEET_MAP_TIMEOUT_MS: process.env.SPREADSHEET_MAP_TIMEOUT_MS || "300000",
  SPREADSHEET_REDUCE_TIMEOUT_MS: process.env.SPREADSHEET_REDUCE_TIMEOUT_MS || "300000",

  // Written Questions (Convex env names must be < 40 chars; long names use WQ_ prefix)
  WRITTEN_QUESTIONS_MAP_CHUNK_TOKENS: process.env.WRITTEN_QUESTIONS_MAP_CHUNK_TOKENS || "5000",
  WRITTEN_QUESTIONS_REDUCE_CHUNK_TOKENS:
    process.env.WRITTEN_QUESTIONS_REDUCE_CHUNK_TOKENS || "10000",
  WRITTEN_QUESTIONS_MAP_TIMEOUT_MS: process.env.WRITTEN_QUESTIONS_MAP_TIMEOUT_MS || "300000",
  WRITTEN_QUESTIONS_REDUCE_TIMEOUT_MS: process.env.WRITTEN_QUESTIONS_REDUCE_TIMEOUT_MS || "300000",
  WRITTEN_QUESTIONS_MIN_QUESTIONS_PER_CHUNK: process.env.WQ_MIN_QUESTIONS_PER_CHUNK || "2",
  WRITTEN_QUESTIONS_MAX_QUESTIONS_PER_CHUNK: process.env.WQ_MAX_QUESTIONS_PER_CHUNK || "30",
  WRITTEN_QUESTIONS_MIN_CHUNKS: process.env.WRITTEN_QUESTIONS_MIN_CHUNKS || "2",
  WRITTEN_QUESTIONS_REDUCE_MAX_TOKENS: process.env.WRITTEN_QUESTIONS_REDUCE_MAX_TOKENS || "32000",
  WRITTEN_QUESTIONS_MAX_COLLAPSE_DEPTH: process.env.WRITTEN_QUESTIONS_MAX_COLLAPSE_DEPTH || "3",
  WRITTEN_QUESTIONS_DYNAMIC_BUFFER_MULTIPLIER: process.env.WQ_DYNAMIC_BUFFER_MULTIPLIER || "1.5",
  WRITTEN_QUESTIONS_CHUNK_COVERAGE_THRESHOLD: process.env.WQ_CHUNK_COVERAGE_THRESHOLD || "0.7",

  // Stripe
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY || "",
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET || "",
  STRIPE_PRO_MONTHLY_PRICE_ID: process.env.STRIPE_PRO_MONTHLY_PRICE_ID || "",
  STRIPE_PRO_YEARLY_PRICE_ID: process.env.STRIPE_PRO_YEARLY_PRICE_ID || "",

  // Chat (RAG + reranking)
  CHAT_LLM_TEMPERATURE: process.env.CHAT_LLM_TEMPERATURE ?? "0.2",
  CHAT_VECTOR_MATCH_THRESHOLD: process.env.CHAT_VECTOR_MATCH_THRESHOLD ?? "0.4",
  CHAT_VECTOR_MATCH_COUNT: process.env.CHAT_VECTOR_MATCH_COUNT ?? "25",
  CHAT_RERANK_THRESHOLD: process.env.CHAT_RERANK_THRESHOLD ?? "10",
  CHAT_RERANK_TOP_N: process.env.CHAT_RERANK_TOP_N ?? "7",
  CHAT_MAX_RESULTS: process.env.CHAT_MAX_RESULTS ?? "7",
  /** Top merged chunks passed to the answer model (citation indices match references). */
  CHAT_MAX_CONTEXT_CHUNKS: process.env.CHAT_MAX_CONTEXT_CHUNKS ?? "15",
  /** Estimated-token budget for prior conversation turns (not including the current user message). */
  CHAT_HISTORY_TOKEN_BUDGET: process.env.CHAT_HISTORY_TOKEN_BUDGET ?? "4000",
  /** Grounding: async (stream-first + warn), sync (validate + strict retry before stream), off. */
  CHAT_GROUNDING_MODE: process.env.CHAT_GROUNDING_MODE ?? "async",
  /** Whole-answer vs cited-chunks embedding similarity bar (grounding_validator). */
  GROUNDING_SIMILARITY_THRESHOLD: process.env.GROUNDING_SIMILARITY_THRESHOLD ?? "0.30",

  // Hybrid Search (NEW)
  CHAT_ENABLE_HYBRID_SEARCH: process.env.CHAT_ENABLE_HYBRID_SEARCH ?? "true",
  CHAT_KEYWORD_MATCH_COUNT: process.env.CHAT_KEYWORD_MATCH_COUNT ?? "50",
  CHAT_RRF_K: process.env.CHAT_RRF_K ?? "60",
  CHAT_HYBRID_THRESHOLD: process.env.CHAT_HYBRID_THRESHOLD ?? "0.012",

  // ZeroEntropy (reranking)
  ZEROENTROPY_API_KEY: process.env.ZEROENTROPY_API_KEY || "",
  ZEROENTROPY_RERANK_MODEL: process.env.ZEROENTROPY_RERANK_MODEL || "zerank-2",

  // Convex deployment info
  CONVEX_CLOUD_URL: process.env.CONVEX_CLOUD_URL || "",
};
